from pathlib import Path
import json

html_path=Path('RAH-HOME-CONTROL.html')
html=html_path.read_text(encoding='utf-8')
assert 'grunnsystem v1.12' in html
html=html.replace('Punkt 1 · grunnsystem v1.12','Punkt 1 · grunnsystem v1.13')
html=html.replace('v1.12: oppretting, statusendring, redigering og fjerning av enheter er transaksjonssikre ved lagringsfeil. Neste: samme sikkerhetsmønster for rom, skjermer og noder. Nettverkssøk og clustering står fortsatt i veikartet.','v1.13: rom, enheter, skjermer og cluster-noder rulles tilbake ved lokal lagringsfeil. Neste: stabilitetsgate og backup av Home Control-konfigurasjonen. Nettverkssøk og clustering står fortsatt i veikartet.')

old_rooms="function renderRooms(){rooms.innerHTML='';state.rooms.forEach(r=>{const e=document.createElement('article');e.className='room'+(r.active?' active':'');e.innerHTML=`<div class=\"top\"><h2>${r.icon} ${r.name}</h2><span class=\"status ${r.active?'':'off'}\">${r.active?'AKTIV':'KLAR'}</span></div><div class=\"buttons\" style=\"margin-top:14px\"><button class=\"primary\" data-room=\"${r.id}\">${r.active?'Slå av':'Aktiver'}</button><button data-main=\"${r.id}\">Hovedrom</button></div>`;rooms.appendChild(e)});document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{const r=state.rooms.find(x=>x.id===b.dataset.room);r.active=!r.active;save();renderAll()});document.querySelectorAll('[data-main]').forEach(b=>b.onclick=()=>{state.rooms.forEach(r=>r.active=r.id===b.dataset.main);save();renderAll()})}"
new_rooms="function renderRooms(){rooms.innerHTML='';state.rooms.forEach(r=>{const e=document.createElement('article');e.className='room'+(r.active?' active':'');e.innerHTML=`<div class=\"top\"><h2>${r.icon} ${r.name}</h2><span class=\"status ${r.active?'':'off'}\">${r.active?'AKTIV':'KLAR'}</span></div><div class=\"buttons\" style=\"margin-top:14px\"><button class=\"primary\" data-room=\"${r.id}\">${r.active?'Slå av':'Aktiver'}</button><button data-main=\"${r.id}\">Hovedrom</button></div>`;rooms.appendChild(e)});document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{const r=state.rooms.find(x=>x.id===b.dataset.room);if(!r)return showError('Rommet finnes ikke lenger.');hideActionNotice();const previousActive=r.active;r.active=!r.active;if(!save()){r.active=previousActive;showError('Romstatusen ble rullet tilbake fordi lokal lagring feilet.');}else showActionNotice(`Romstatus for «${r.name}» er lagret lokalt.`);renderAll()});document.querySelectorAll('[data-main]').forEach(b=>b.onclick=()=>{const target=state.rooms.find(x=>x.id===b.dataset.main);if(!target)return showError('Rommet finnes ikke lenger.');hideActionNotice();const previousRooms=clone(state.rooms);state.rooms.forEach(r=>r.active=r.id===b.dataset.main);if(!save()){state.rooms=previousRooms;showError('Valg av hovedrom ble rullet tilbake fordi lokal lagring feilet.');}else showActionNotice(`«${target.name}» er satt som hovedrom og lagret lokalt.`);renderAll()})}"
assert old_rooms in html, 'renderRooms baseline not found'
html=html.replace(old_rooms,new_rooms)

old_screens="function renderScreens(){screens.innerHTML='';state.screens.forEach(s=>{const e=document.createElement('article');e.className='panel';e.innerHTML=`<div class=\"top\"><h2>${s.name}</h2><span class=\"status ${s.active?'':'off'}\">${s.active?'AKTIV':'FRAKOBLET'}</span></div><div class=\"items\"><div class=\"item\"><span>Rom</span><span>${s.room}</span></div><div class=\"item\"><span>Modus</span><span>${s.mode}</span></div></div><button data-screen=\"${s.id}\">${s.active?'Deaktiver':'Aktiver teststatus'}</button>`;screens.appendChild(e)});screenCount.textContent=`${state.screens.filter(s=>s.active).length} aktive`;document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{const s=state.screens.find(x=>x.id===b.dataset.screen);s.active=!s.active;save();renderAll()})}"
new_screens="function renderScreens(){screens.innerHTML='';state.screens.forEach(s=>{const e=document.createElement('article');e.className='panel';e.innerHTML=`<div class=\"top\"><h2>${s.name}</h2><span class=\"status ${s.active?'':'off'}\">${s.active?'AKTIV':'FRAKOBLET'}</span></div><div class=\"items\"><div class=\"item\"><span>Rom</span><span>${s.room}</span></div><div class=\"item\"><span>Modus</span><span>${s.mode}</span></div></div><button data-screen=\"${s.id}\">${s.active?'Deaktiver':'Aktiver teststatus'}</button>`;screens.appendChild(e)});screenCount.textContent=`${state.screens.filter(s=>s.active).length} aktive`;document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{const s=state.screens.find(x=>x.id===b.dataset.screen);if(!s)return showError('Skjermen finnes ikke lenger.');hideActionNotice();const previousActive=s.active;s.active=!s.active;if(!save()){s.active=previousActive;showError('Skjermstatusen ble rullet tilbake fordi lokal lagring feilet.');}else showActionNotice(`Skjermstatus for «${s.name}» er lagret lokalt.`);renderAll()})}"
assert old_screens in html, 'renderScreens baseline not found'
html=html.replace(old_screens,new_screens)

old_nodes="function renderNodes(){nodes.innerHTML='';state.nodes.forEach(n=>{const e=document.createElement('article');e.className='panel';e.innerHTML=`<div class=\"top\"><h2>${n.name}</h2><span class=\"status ${n.ready?'':'off'}\">${n.ready?'KLAR':'VENTER'}</span></div><div class=\"items\"><div class=\"item\"><span>Rolle</span><span>${n.role}</span></div><div class=\"item\"><span>Forbindelse</span><span>${n.connection}</span></div></div><button data-node=\"${n.id}\">${n.ready?'Ventemodus':'Marker klar'}</button>`;nodes.appendChild(e)});nodeCount.textContent=`${state.nodes.filter(n=>n.ready).length} klare`;document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{const n=state.nodes.find(x=>x.id===b.dataset.node);n.ready=!n.ready;save();renderAll()})}"
new_nodes="function renderNodes(){nodes.innerHTML='';state.nodes.forEach(n=>{const e=document.createElement('article');e.className='panel';e.innerHTML=`<div class=\"top\"><h2>${n.name}</h2><span class=\"status ${n.ready?'':'off'}\">${n.ready?'KLAR':'VENTER'}</span></div><div class=\"items\"><div class=\"item\"><span>Rolle</span><span>${n.role}</span></div><div class=\"item\"><span>Forbindelse</span><span>${n.connection}</span></div></div><button data-node=\"${n.id}\">${n.ready?'Ventemodus':'Marker klar'}</button>`;nodes.appendChild(e)});nodeCount.textContent=`${state.nodes.filter(n=>n.ready).length} klare`;document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{const n=state.nodes.find(x=>x.id===b.dataset.node);if(!n)return showError('Cluster-noden finnes ikke lenger.');hideActionNotice();const previousReady=n.ready;n.ready=!n.ready;if(!save()){n.ready=previousReady;showError('Node-statusen ble rullet tilbake fordi lokal lagring feilet.');}else showActionNotice(`Node-status for «${n.name}» er lagret lokalt.`);renderAll()})}"
assert old_nodes in html, 'renderNodes baseline not found'
html=html.replace(old_nodes,new_nodes)
html_path.write_text(html,encoding='utf-8')

manifest_path=Path('RAH-HOME-CONTROL-VERSION.json')
m=json.loads(manifest_path.read_text(encoding='utf-8'))
assert m['version']=='1.12.0'
m['version']='1.13.0';m['stage']='working-transaction-safe-local-control';m['released_at']='2026-08-13'
m['features'].update({
  'room_status_storage_rollback':True,
  'main_room_storage_rollback':True,
  'screen_status_storage_rollback':True,
  'cluster_node_status_storage_rollback':True,
  'room_screen_node_mutations_transaction_safe':True,
  'all_primary_local_status_mutations_transaction_safe':True
})
m['next_milestone']='home-control-stability-gate-and-config-backup'
manifest_path.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

Path('tests/rah-home-control.test.mjs').write_text(r'''import assert from 'node:assert/strict';import fs from 'node:fs';
const html=fs.readFileSync('RAH-HOME-CONTROL.html','utf8');const manifest=JSON.parse(fs.readFileSync('RAH-HOME-CONTROL-VERSION.json','utf8'));
assert.equal(manifest.product,'RAH Home Control');assert.equal(manifest.version,'1.13.0');assert.equal(manifest.local_only,true);assert.equal(manifest.features.device_mutations_transaction_safe,true);assert.equal(manifest.features.room_status_storage_rollback,true);assert.equal(manifest.features.main_room_storage_rollback,true);assert.equal(manifest.features.screen_status_storage_rollback,true);assert.equal(manifest.features.cluster_node_status_storage_rollback,true);assert.equal(manifest.features.room_screen_node_mutations_transaction_safe,true);assert.equal(manifest.features.all_primary_local_status_mutations_transaction_safe,true);assert.equal(manifest.features.automatic_network_discovery,false);assert.equal(manifest.features.automatic_task_execution,false);
assert.match(html,/grunnsystem v1\.13/);
const roomsStart=html.indexOf('function renderRooms()'),devicesStart=html.indexOf('function filteredDevices()',roomsStart);assert.ok(roomsStart>0&&devicesStart>roomsStart);const rooms=html.slice(roomsStart,devicesStart);assert.match(rooms,/const previousActive=r\.active/);assert.match(rooms,/r\.active=previousActive/);assert.match(rooms,/Romstatusen ble rullet tilbake/);assert.match(rooms,/const previousRooms=clone\(state\.rooms\)/);assert.match(rooms,/state\.rooms=previousRooms/);assert.match(rooms,/Valg av hovedrom ble rullet tilbake/);
const screensStart=html.indexOf('function renderScreens()'),nodesStart=html.indexOf('function renderNodes()',screensStart);assert.ok(screensStart>0&&nodesStart>screensStart);const screens=html.slice(screensStart,nodesStart);assert.match(screens,/const previousActive=s\.active/);assert.match(screens,/s\.active=previousActive/);assert.match(screens,/Skjermstatusen ble rullet tilbake/);
const tasksStart=html.indexOf('function renderTasks()',nodesStart);assert.ok(tasksStart>nodesStart);const nodes=html.slice(nodesStart,tasksStart);assert.match(nodes,/const previousReady=n\.ready/);assert.match(nodes,/n\.ready=previousReady/);assert.match(nodes,/Node-statusen ble rullet tilbake/);
assert.doesNotMatch(html,/fetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon/,'Home Control v1.13 must not add network activity.');
const script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];assert.ok(script);new Function(script);
console.log('RAH Home Control v1.13: room, main-room, screen and cluster-node status mutations roll back on local storage failure.');
''',encoding='utf-8')
