import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';

const m=JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8'));
const release=JSON.parse(fs.readFileSync('RAH-CC24-NODE14-STABLE-RELEASE.json','utf8'));
const nodeRelease=JSON.parse(fs.readFileSync('RAH-NODE14-RAVEN-STATUS-STABLE-RELEASE.json','utf8'));
const up=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER.ps1','utf8');
const launcher=fs.readFileSync('DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','utf8');
const nodeBat=fs.readFileSync('START-RAH-NODE-AGENT.bat','utf8');
const nodeSh=fs.readFileSync('START-RAH-NODE-AGENT.sh','utf8');
const blob=p=>execFileSync('git',['hash-object',p],{encoding:'utf8'}).trim();
const revBlob=(c,p)=>execFileSync('git',['rev-parse',`${c}:${p}`],{encoding:'utf8'}).trim();
function pinnedCommit(){const x=up.match(/\$ReleaseCommit="([0-9a-f]{40})"/);assert.ok(x,'40-char immutable ReleaseCommit');return x[1]}

const historicalGeneration8=[
'RAH-COMMAND-CENTER-V2.3.html','RAH-COMMAND-CENTER-V2.3-CANDIDATE.html','rah-command-center-core-v2.3-candidate.js','rah-command-center-core-v2.3.js','RAH-CC23-FLEET-SNAPSHOT-REGISTRY-BINDING-CANDIDATE.json','RAH-CC23-NODE13-STABLE-RELEASE.json',
'RAH-COMMAND-CENTER-V2.2.html','RAH-COMMAND-CENTER-V2.2-CANDIDATE.html','rah-command-center-core-v2.2-candidate.js','rah-command-center-core-v2.2.js','RAH-CC22-FLEET-SNAPSHOT-INVALIDATION-CANDIDATE.json','RAH-CC22-NODE13-STABLE-RELEASE.json',
'RAH-COMMAND-CENTER-V2.1.html','RAH-COMMAND-CENTER-V2.1-CANDIDATE.html','rah-command-center-core-v2.1-candidate.js','rah-command-center-core-v2.1.js','RAH-CC21-FLEET-SNAPSHOT-CANDIDATE.json','RAH-CC21-NODE13-STABLE-RELEASE.json',
'RAH-COMMAND-CENTER-V2.0.html','RAH-COMMAND-CENTER-V2.0-CANDIDATE.html','rah-command-center-core-v2.0-candidate.js','rah-command-center-core-v2.0.js','RAH-CC20-PRECOMMITTED-REQUESTER-CONTEXT-CANDIDATE.json','RAH-CC20-NODE13-STABLE-RELEASE.json',
'RAH-COMMAND-CENTER-V1.9.html','RAH-COMMAND-CENTER-V1.9-CANDIDATE.html','rah-command-center-core-v1.9-candidate.js','rah-command-center-core-v1.9.js','RAH-CC19-IMMUTABLE-MUTATING-INTENT-CANDIDATE.json','RAH-CC19-NODE13-STABLE-RELEASE.json',
'RAH-COMMAND-CENTER-V1.8.html','RAH-COMMAND-CENTER-V1.8-CANDIDATE.html','RAH-COMMAND-CENTER-V1.7.html','RAH-COMMAND-CENTER-V1.7-CANDIDATE.html','RAH-COMMAND-CENTER-V1.2.html','rah-command-center-core.js','rah-command-center-core-v1.3.js','rah-command-center-core-v1.4.js','rah-command-center-core-v1.5-candidate.js','rah-command-center-core-v1.5.js','rah-command-center-core-v1.6-candidate.js','rah-command-center-core-v1.6.js','rah-command-center-core-v1.7-candidate.js','rah-command-center-core-v1.7.js','rah-command-center-core-v1.8-candidate.js','rah-command-center-core-v1.8.js','DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','rah-node-agent.py','rah-node-agent-v0.9.py','rah-node-agent-v1.0-candidate.py','rah-node-agent-v1.0.py','rah-node-agent-v1.1-candidate.py','rah-node-agent-v1.1.py','rah-node-agent-v1.2-candidate.py','rah-node-agent-v1.3-candidate.py','rah-node-agent-v1.3.py','START-RAH-NODE-AGENT.bat','START-RAH-NODE-AGENT.sh','RAH-CC17-NODE13-STABLE-RELEASE.json','RAH-CC18-ONE-SHOT-MUTATING-APPROVAL-CANDIDATE.json','RAH-CC18-NODE13-STABLE-RELEASE.json'];

test('generation 9 is exact 71-file superset of historical generation 8',()=>{assert.equal(m.canonical_package_generation,9);assert.equal(m.package_files.length,71);assert.equal(new Set(m.package_files).size,71);for(const p of historicalGeneration8)assert.ok(m.package_files.includes(p),`historical artifact retained: ${p}`);for(const p of m.package_files)assert.ok(fs.existsSync(p),p)});
test('pinned updater commit contains exact canonical package blobs',()=>{const c=pinnedCommit();for(const p of m.package_files)assert.equal(revBlob(c,p),blob(p),p);assert.equal(revBlob(c,'RAH-COMMAND-CENTER-VERSION.json'),blob('RAH-COMMAND-CENTER-VERSION.json'));assert.match(up,/commit\.verification\.verified/);assert.match(up,/git\/trees\/\$\{TreeSha\}\?recursive=1/);assert.match(up,/Get-GitBlobSha/);assert.match(up,/recovery gate er resolved/i);assert.match(up,/Write-JournalDurable/);assert.match(up,/Backup-Transaction/);assert.match(up,/Restore-Transaction/)});
test('canonical entrypoints select CC2.4 and Node1.4 only',()=>{assert.match(launcher,/RAH-COMMAND-CENTER-V2\.4\.html/);assert.doesNotMatch(launcher,/RAH-COMMAND-CENTER-V2\.3\.html/);for(const text of [nodeBat,nodeSh]){assert.match(text,/rah-node-agent-v1\.4\.py/);assert.doesNotMatch(text,/rah-node-agent-v1\.3\.py/)}});
test('Commander route cannot expand into generic execution',()=>{assert.equal(release.ravenCommanderVersion,'rah-cc-raven-commander-v1');assert.equal(release.ravenStatusProtocol,'rah-node-raven-status-v1');assert.equal(release.ravenStatusRoute,'/raven/status');assert.equal(release.ravenStatusFixedCapability,'system-inventory');const r=release.authoritySurface.newRoute;assert.deepEqual({path:r.path,method:r.method,mutating:r.mutating,requiresCapability:r.requiresCapability,fixedRavenCapability:r.fixedRavenCapability,localRavenHop:r.localRavenHop,callerControlledArguments:r.callerControlledArguments,callerControlledPath:r.callerControlledPath,arbitraryCommands:r.arbitraryCommands,backgroundPolling:r.backgroundPolling,automaticExecution:r.automaticExecution,tokenPersistence:r.tokenPersistence},{path:'/raven/status',method:'GET',mutating:false,requiresCapability:'compute',fixedRavenCapability:'system-inventory',localRavenHop:'http://127.0.0.1:18765',callerControlledArguments:false,callerControlledPath:false,arbitraryCommands:false,backgroundPolling:false,automaticExecution:false,tokenPersistence:false});for(const forbidden of ['arbitrary-shell','generic-command-execution','generic-process-launch','generic-file-api','caller-controlled-raven-capability','caller-controlled-raven-url','caller-controlled-path','caller-controlled-generic-arguments','background-polling','native-raven-remote-control-api'])assert.ok(nodeRelease.forbiddenRuntimeExpansion.includes(forbidden),forbidden)});
test('generation 9 direct rollback remains CC2.3 Node1.3 with no migration',()=>{assert.equal(release.directRollback.commandCenterVersion,'2.3.0');assert.equal(release.directRollback.nodeAgentVersion,'1.3.0');assert.equal(release.directRollback.dataMigration,'none');assert.equal(release.directRollback.secretMigration,'none');assert.equal(release.directRollback.registryMigration,'none')});
