import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{execFileSync}from'node:child_process';
const root=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER.ps1','utf8'),v2=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER-V2.ps1','utf8'),candidate=JSON.parse(fs.readFileSync('RAH-CC-UPDATER-V2-VERSION.json','utf8')),stable=JSON.parse(fs.readFileSync('RAH-CC-UPDATER-V2-STABLE-RELEASE.json','utf8')),integrity=JSON.parse(fs.readFileSync('RAH-CC17-PACKAGE-INTEGRITY.json','utf8')),cc=JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8')),raven=JSON.parse(fs.readFileSync('RAH-RAVEN-VERSION.json','utf8'));
function gitBlob(path){const dirty=execFileSync('git',['status','--porcelain','--',path],{encoding:'utf8'}).trim();return dirty?execFileSync('git',['hash-object',path],{encoding:'utf8'}).trim():execFileSync('git',['rev-parse',`HEAD:${path}`],{encoding:'utf8'}).trim()}
test('Stable activation pins unchanged Candidate V2 and offline root wrapper',()=>{assert.equal(candidate.stage,'feature-candidate');assert.equal(candidate.active_from_root_wrapper,false);assert.equal(stable.product,'RAH Command Center Updater');assert.equal(stable.version,'2.0.0');assert.equal(stable.stage,'stable-release');assert.equal(stable.active_from_root_wrapper,true);assert.equal(stable.runtime.gitBlobSha,gitBlob('UPDATE-RAH-COMMAND-CENTER-V2.ps1'));assert.equal(stable.candidateManifest.gitBlobSha,gitBlob('RAH-CC-UPDATER-V2-VERSION.json'));assert.equal(stable.rootWrapper.gitBlobSha,gitBlob('UPDATE-RAH-COMMAND-CENTER.ps1'));assert.equal(stable.directRollback.legacyUpdater.gitBlobSha,gitBlob('UPDATE-RAH-COMMAND-CENTER-V1-LEGACY.ps1'));assert.equal(stable.integrityManifest.gitBlobSha,gitBlob('RAH-CC17-PACKAGE-INTEGRITY.json'))});
test('root wrapper has no network and no automatic legacy fallback',()=>{assert.match(root,/UPDATE-RAH-COMMAND-CENTER-V2\.ps1/);assert.match(root,/RAH-CC-UPDATER-V2-STABLE-RELEASE\.json/);assert.match(root,/Get-GitBlobSha1/);assert.match(root,/startes aldri automatisk/);assert.doesNotMatch(root,/Invoke-WebRequest|Invoke-RestMethod|raw\.githubusercontent\.com|api\.github\.com|https?:\/\//i);assert.doesNotMatch(root,/&\s*\$LegacyPath/)});
test('V2 Candidate runtime retains immutable full-stage integrity behavior',()=>{assert.match(v2,/Resolve-VerifiedRepositoryCommit/);assert.match(v2,/commitInfo\.commit\.verification\.verified/);assert.match(v2,/Assert-IntegrityManifest/);assert.match(v2,/packagefiler er staged/);assert.match(v2,/Restore-OnFailure/);assert.doesNotMatch(v2,/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$RepoBranch/)});
test('canonical manifest activates integrity generation without runtime authority change',()=>{assert.equal(cc.version,'1.7.0');assert.equal(cc.package_integrity_manifest,'RAH-CC17-PACKAGE-INTEGRITY.json');assert.equal(cc.canonical_package_generation,3);assert.equal(cc.release_gate.gate_version,'2.1.0');assert.equal(cc.features.package_integrity_manifest,true);assert.equal(cc.features.package_integrity_git_blob_sha1,true);assert.equal(cc.features.manual_updater_verifies_package_blob_before_replace,true);assert.equal(cc.features.manual_updater_full_stage_before_install,true);assert.equal(cc.features.manual_updater_rollback_on_failure,true)});
test('integrity manifest exactly pins 25 non-self package files',()=>{assert.equal(integrity.product,'RAH Raven Command Center Package Integrity');assert.equal(integrity.schemaVersion,1);assert.equal(integrity.canonical_version,'1.7.0');assert.equal(integrity.algorithm,'git-blob-sha1');assert.equal(integrity.self_hashed,false);assert.equal(integrity.hashed_files.length,25);for(const row of integrity.hashed_files)assert.equal(row.gitBlobSha,gitBlob(row.path),row.path)});
test('Raven package distributes CC updater V2 activation chain',()=>{for(const file of ['UPDATE-RAH-COMMAND-CENTER.ps1','UPDATE-RAH-COMMAND-CENTER-V1-LEGACY.ps1','UPDATE-RAH-COMMAND-CENTER-V2.ps1','RAH-CC-UPDATER-V2-VERSION.json','RAH-CC-UPDATER-V2-STABLE-RELEASE.json','RAH-CC17-PACKAGE-INTEGRITY.json'])assert.ok(raven.files.includes(file),file);for(const [key,value]of Object.entries({command_center_updater_v2_stable:true,command_center_updater_root_wrapper_network_requests:false,command_center_updater_runtime_git_blob_pin_required:true,command_center_updater_full_stage_before_install:true,command_center_updater_package_integrity_git_blob_sha1:true,command_center_updater_rollback_on_failure:true,command_center_updater_legacy_auto_fallback:false}))assert.equal(raven.privacy[key],value,key)});
test('Stable release is truthful about rollback and transition',()=>{assert.equal(stable.directRollback.security_regression,'removes V2 full-stage integrity gate and root runtime pinning');assert.equal(stable.directRollback.dataMigration,'none');assert.equal(stable.directRollback.secretMigration,'none');assert.equal(stable.directRollback.registryMigration,'none');assert.equal(stable.known_transition_limit.existing_manual_cc_updater_does_not_self_upgrade_to_v2,true);assert.equal(stable.known_transition_limit.raven_updater_v2_is_activation_bridge,true);assert.equal(stable.known_transition_limit.claim_entire_historical_transition_is_v2_hardened,false)});
