import assert from 'node:assert/strict';import fs from 'node:fs';
const html=fs.readFileSync('RAH-HOME-CONTROL.html','utf8');const manifest=JSON.parse(fs.readFileSync('RAH-HOME-CONTROL-VERSION.json','utf8'));
assert.equal(manifest.product,'RAH Home Control');assert.equal(manifest.version,'1.19.0');assert.equal(manifest.local_only,true);assert.equal(manifest.features.device_mutations_transaction_safe,true);assert.equal(manifest.features.room_screen_node_mutations_transaction_safe,true);assert.equal(manifest.features.all_primary_local_status_mutations_transaction_safe,true);assert.equal(manifest.features.standard_reset_storage_rollback,true);assert.equal(manifest.features.standard_reset_state_and_filters_atomic,true);assert.equal(manifest.features.filter_reset_storage_rollback,true);assert.equal(manifest.features.filter_button_storage_rollback,true);assert.equal(manifest.features.filter_mutations_transaction_safe,true);assert.equal(manifest.features.filter_load_parse_error_visible,true);assert.equal(manifest.features.filter_load_parse_error_safe_fallback,true);assert.equal(manifest.features.filter_load_partial_invalid_visible,true);assert.equal(manifest.features.automatic_network_discovery,false);assert.equal(manifest.features.automatic_task_execution,false);assert.equal(manifest.features.external_network_calls,false);
assert.match(html,/stabil lokal kontroll v1\.24/);assert.match(html,/v1\.24:/);assert.match(html,/romnavn, rom-ID-er, enhets-ID-er og normaliserte enhetsnavn må være unike/);assert.match(html,/satt IPv4 må være gyldig og unik/);assert.match(html,/Romstatusen ble rullet tilbake/);assert.match(html,/Statusendringen ble rullet tilbake/);assert.match(html,/Skjermstatusen ble rullet tilbake/);assert.match(html,/Node-statusen ble rullet tilbake/);assert.match(html,/const previousState=clone\(state\),previousEditingDeviceId=editingDeviceId,previousStatusFilter=statusFilter,previousRoomFilter=roomFilter/);assert.match(html,/const stateSaved=save\(\),filtersSaved=saveFilters\(\)/);assert.match(html,/if\(stateSaved&&filtersSaved\)/);assert.match(html,/state=previousState;editingDeviceId=previousEditingDeviceId;statusFilter=previousStatusFilter;roomFilter=previousRoomFilter/);assert.match(html,/Gjenoppretting av standarddata ble rullet tilbake fordi lokal lagring feilet/);
assert.match(html,/const previousStatusFilter=statusFilter,previousRoomFilter=roomFilter,previousEditingDeviceId=editingDeviceId/);assert.match(html,/Filter-nullstillingen ble rullet tilbake fordi lokal lagring feilet/);assert.match(html,/const previousStatusFilter=statusFilter,previousEditingDeviceId=editingDeviceId/);assert.match(html,/Statusfilteret ble rullet tilbake fordi lokal lagring feilet/);assert.match(html,/const previousRoomFilter=roomFilter,previousEditingDeviceId=editingDeviceId/);assert.match(html,/Romfilteret ble rullet tilbake fordi lokal lagring feilet/);
assert.match(html,/const parsed=JSON\.parse\(raw\),statusValid=STATUS_FILTERS\.includes\(parsed&&parsed\.status\),roomValid=ROOM_FILTERS\.includes\(parsed&&parsed\.room\)/);assert.match(html,/if\(!statusValid\|\|!roomValid\)showError\('Lagrede filtervalg inneholdt verdier som ikke støttes\. Ugyldige valg bruker standardverdi; gyldige valg beholdes\.'\)/);assert.match(html,/return\{status:statusValid\?parsed\.status:'all',room:roomValid\?parsed\.room:'all'\}/);assert.match(html,/catch\{showError\('Lagrede filtervalg kunne ikke leses\. Standardfiltrene Alle \/ Alle rom brukes midlertidig\.'\);return\{status:'all',room:'all'\}\}/);
assert.doesNotMatch(html,/fetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon/,'Home Control baseline must not add external network activity.');
const script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];assert.ok(script);new Function(script);
console.log('RAH Home Control legacy Stable baseline: transaction safety, filter fallback and network-free runtime are preserved against v1.24 HTML.');
