import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const ps=fs.readFileSync('UPDATE-RAH-RAVEN-V2.ps1','utf8');
const manifest=JSON.parse(fs.readFileSync('RAH-RAVEN-UPDATER-V2-VERSION.json','utf8'));
const raven=JSON.parse(fs.readFileSync('RAH-RAVEN-VERSION.json','utf8'));
const cc=JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8'));
const stableCore={raven_vision:'0.6',raven_council:'0.3',agent_runner:'0.3',memory_sync:'0.2',mission_control:'2.9',project_focus:'2.4',raven_core:'1.12',raven_now:'2.17',raven_studio:'2.8'};

test('Updater v2 Candidate is inactive and authority-neutral',()=>{assert.equal(manifest.product,'RAH Raven Updater');assert.equal(manifest.version,'2.0.0');assert.equal(manifest.stage,'feature-candidate');assert.equal(manifest.active_from_root_wrapper,false);assert.equal(manifest.authority_delta,'none');assert.equal(manifest.release_gate.status,'candidate');assert.equal(manifest.release_gate.runtime_files_frozen,false);assert.equal(manifest.release_gate.stable_activation_requires_separate_promotion,true);assert.deepEqual(manifest.stable_core_preserved,stableCore);assert.deepEqual(raven.release_gate.stable_components,stableCore);assert.equal(cc.version,'1.7.0')});

test('network resolution uses one GitHub-verified commit and immutable raw base',()=>{assert.match(ps,/Resolve-VerifiedRepositoryCommit/);assert.match(ps,/commitInfo\.commit\.verification\.verified/);assert.match(ps,/\$RawBase="https:\/\/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$ResolvedCommit"/);assert.match(ps,/Invoke-WebRequest[^\n]+\$RawBase\/\$ManifestName/);assert.match(ps,/Invoke-WebRequest[^\n]+\$RawBase\/\$encoded/);assert.doesNotMatch(ps,/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$RepoBranch/);assert.doesNotMatch(ps,/raw\.githubusercontent\.com\/NilsRa73\/rah-platform\/main/);assert.equal(manifest.network_model.raw_mutable_main_downloads,false);assert.equal(manifest.network_model.single_resolved_commit_per_run,true)});

test('manifest path boundary and staged-before-install model are explicit',()=>{assert.match(ps,/Get-SafeTargetPath/);assert.match(ps,/IsPathRooted/);assert.match(ps,/Contains\('\.\.'\)/);assert.match(ps,/StartsWith\(\$baseFull/);assert.match(ps,/\$StageRoot=Join-Path/);assert.match(ps,/foreach\(\$relative in \$files\)[\s\S]*Invoke-WebRequest[\s\S]*Assert-StagedCanonicalCommandCenter[\s\S]*New-Item -ItemType Directory -Path \$BackupDir/);assert.equal(manifest.installation_model.download_all_to_stage_before_install,true);assert.equal(manifest.installation_model.backup_before_replace,true);assert.equal(manifest.installation_model.rollback_on_install_failure,true)});

test('critical bootstrap closure includes updater bridge and canonical CC 1.7 anchors',()=>{for(const file of manifest.critical_files){assert.match(ps,new RegExp(file.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))}assert.ok(manifest.critical_files.includes('UPDATE-RAH-COMMAND-CENTER.ps1'));assert.ok(manifest.critical_files.includes('RAH-COMMAND-CENTER-V1.7.html'));assert.ok(manifest.critical_files.includes('rah-node-agent-v1.3.py'));assert.ok(manifest.critical_files.includes('RAH-CC17-NODE13-STABLE-RELEASE.json'));assert.match(ps,/Assert-StagedCanonicalCommandCenter/);assert.match(ps,/nodeActionsProtocol-ne'rah-node-actions-v7'/);assert.match(ps,/authProtocol-ne'rah-node-auth-v2'/)});

test('rollback path exists and CC sync occurs only after Raven install',()=>{assert.match(ps,/function Restore-OnFailure/);assert.match(ps,/Starter rollback/);assert.match(ps,/Restore-OnFailure/);const installed=ps.indexOf('Raven $ExpectedRavenVersion installert');const sync=ps.indexOf("Kjører canonical Command Center-sync");assert.ok(installed>0&&sync>installed);assert.match(ps,/& \$ccUpdater -NoStart/)});

test('Candidate does not hide legacy first-hop limitation',()=>{assert.equal(manifest.known_transition_limit.legacy_first_hop_from_pre_v2_updater_uses_old_behavior,true);assert.equal(manifest.known_transition_limit.future_v2_runs_immutable_commit_locked,true);assert.equal(manifest.known_transition_limit.claim_entire_historical_transition_is_immutable,false)});

test('Candidate preserves exact CC authority and forbidden runtime expansion',()=>{assert.deepEqual(manifest.command_center_contract.capabilities,['compute','storage','display','remote-desktop']);assert.deepEqual(manifest.command_center_contract.actions,['storage-summary.read','rustdesk.launch','rustdesk.connect']);assert.deepEqual(manifest.command_center_contract.business_routes,['/health','/actions','/storage','/launch/rustdesk','/handoff/rustdesk']);for(const item of ['new_command_center_capability','new_command_center_action','new_command_center_business_route','unverified_commit_download','mutable_raw_main_download_after_resolution','path_traversal','shell_endpoint','generic_command_endpoint','generic_file_endpoint','native_raven_remote_control_api'])assert.ok(manifest.forbidden.includes(item),item)});
