import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const gate=JSON.parse(fs.readFileSync('RAH-CC23-STABLE-PROMOTION-GATE.json','utf8'));
const manifest=JSON.parse(fs.readFileSync('RAH-CC23-FLEET-SNAPSHOT-REGISTRY-BINDING-CANDIDATE.json','utf8'));
const candidate=require('../rah-command-center-core-v2.3-candidate.js');
const stable=require('../rah-command-center-core-v2.2.js');
const blob=p=>execFileSync('git',['hash-object',p],{encoding:'utf8'}).trim();
const caps=['compute','storage','display','remote-desktop'];const actions=['storage-summary.read','rustdesk.launch','rustdesk.connect'];const routes=['/health','/actions','/storage','/launch/rustdesk','/handoff/rustdesk'];

test('readiness pins exact CC2.2 Stable rollback and Node1.3 baseline',()=>{assert.equal(gate.stage,'stable-readiness');assert.equal(gate.authorityDelta,'none');assert.equal(gate.ravenVersion,'2.0.32');assert.equal(gate.sourceStable.commandCenterVersion,'2.2.0');assert.equal(gate.sourceStable.canonicalPackageGeneration,7);assert.equal(gate.sourceStable.nodeAgentVersion,'1.3.0');for(const p of [gate.sourceStable.releaseManifest,gate.sourceStable.commandCenterCore,gate.sourceStable.commandCenterHtml,gate.sourceStable.nodeAgent])assert.equal(blob(p.path),p.gitBlobSha,p.path);assert.equal(stable.CC_VERSION,'2.2.0')});
test('readiness pins exact immutable CC2.3 Candidate bytes',()=>{assert.equal(gate.candidate.commandCenterVersion,'2.3.0-candidate');assert.equal(gate.candidate.stableRuntimeModified,false);assert.equal(gate.candidate.nodeRuntimeModified,false);for(const p of [gate.candidate.manifest,gate.candidate.commandCenterCore,gate.candidate.commandCenterHtml])assert.equal(blob(p.path),p.gitBlobSha,p.path);assert.equal(candidate.CC_VERSION,'2.3.0-candidate');assert.equal(manifest.candidate,'2.3.0-candidate')});
test('registry binding is event-driven and identity-exact',()=>{const r=gate.registryBindingBoundary;assert.equal(r.version,'rah-cc-fleet-snapshot-registry-binding-v1');assert.equal(r.policy,'prune-row-on-registry-identity-drift');assert.deepEqual(r.identityFields,['deviceId','endpointIp','sessionId']);assert.equal(r.pruneRemovedDevice,true);assert.equal(r.pruneEndpointChange,true);assert.equal(r.pruneNodeSessionChange,true);assert.equal(r.samePageSignal,'device-grid-mutation-observer');assert.equal(r.crossTabSignal,'storage-event-exact-device-registry-key');assert.equal(r.snapshotMemoryOnly,true);assert.equal(r.snapshotPersistence,false);assert.equal(r.tokenPersistence,false);assert.equal(r.timers,false);assert.equal(r.backgroundPolling,false);assert.equal(r.networkDiscovery,false);assert.equal(r.automaticRemoteControl,false);assert.equal(r.nodeAgentChange,false)});
test('exact 4/3/5 authority and CC2.2 failed-refresh boundary remain',()=>{assert.deepEqual(gate.authoritySurface.capabilities,caps);assert.deepEqual(gate.authoritySurface.actions,actions);assert.deepEqual(gate.authoritySurface.businessRoutes,routes);assert.deepEqual(candidate.CAPABILITY_IDS,caps);assert.deepEqual(candidate.ACTION_IDS,actions);assert.deepEqual(candidate.AUTHENTICATED_PATHS,routes);assert.equal(candidate.NODE_ACTIONS_PROTOCOL,'rah-node-actions-v7');assert.equal(candidate.NODE_AUTH_PROTOCOL,'rah-node-auth-v2');assert.equal(candidate.FLEET_SNAPSHOT_FAILURE_POLICY,'invalidate-selected-row-on-refresh-failure');assert.equal(gate.retainedCc22Boundary.selectedRowInvalidatedBeforeFailureRender,true)});
test('promotion remains separate and rollback requires no migration',()=>{const r=gate.stablePromotionRequirements;assert.equal(r.separateRuntimePromotionPrRequired,true);assert.equal(r.targetCommandCenterVersion,'2.3.0');assert.equal(r.targetNodeAgentVersion,'1.3.0');assert.equal(r.canonicalRootPromotionSeparate,true);assert.equal(r.canonicalPackageGenerationIncrementRequired,true);assert.equal(r.ravenMasterSyncSeparate,true);assert.deepEqual(gate.directRollback,{commandCenterVersion:'2.2.0',canonicalPackageGeneration:7,nodeAgentVersion:'1.3.0',dataMigration:'none',secretMigration:'none',registryMigration:'none'})});
test('generic authority expansion remains explicitly forbidden',()=>{for(const x of ['new-capabilities','new-actions','new-business-routes','network-discovery','background-polling','shell','generic-command-execution','generic-process-launch','generic-action-endpoint','generic-file-api','caller-controlled-executable-path','caller-controlled-generic-arguments','native-raven-remote-control-api'])assert.ok(gate.forbidden.includes(x),x)});
