import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const core = require('../rah-command-center-core.js');
const raven = JSON.parse(fs.readFileSync('RAH-RAVEN-VERSION.json','utf8'));
const cc = JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8'));
const html = fs.readFileSync('RAH-COMMAND-CENTER-V0.3.html','utf8');
const launcher = fs.readFileSync('DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','utf8');
const expected={raven_vision:'0.6',raven_council:'0.3',agent_runner:'0.3',memory_sync:'0.2',mission_control:'2.9',project_focus:'2.4',raven_core:'1.12',raven_now:'2.17',raven_studio:'2.8'};

assert.equal(cc.version,'0.3.3');
assert.equal(cc.stage,'stable-bugfix-candidate');
assert.equal(cc.runtime_feature_change,false);
assert.equal(cc.next_milestone,'stable-gate');
assert.equal(cc.release_gate.status,'candidate');
assert.equal(cc.release_gate.stable_raven_runtime_frozen,true);
assert.equal(cc.features.stable_runtime_files_changed,false);
assert.equal(cc.features.offline_first_one_click_launcher,true);
assert.equal(cc.features.launcher_network_requests,false);
assert.equal(cc.features.automatic_update_on_launch,false);
assert.equal(cc.features.manual_updater_requires_explicit_launch,true);
assert.equal(cc.features.manual_updater_network_requests,true);
assert.equal(cc.features.manual_updater_verified_commit_resolution,true);
assert.equal(cc.features.manual_updater_immutable_commit_downloads,true);
assert.equal(cc.features.manual_updater_stable_manifest_required,true);
assert.equal(cc.features.manual_updater_fixed_package_allowlist,true);
assert.equal(cc.features.raven_updater_remote_cc_bootstrap,false);
assert.equal(cc.features.bridge_health_check_explicit_only,true);
assert.equal(cc.features.automatic_agent_execution,false);
assert.equal(cc.features.automatic_mission_mutation,false);
assert.equal(cc.features.automatic_project_activation,false);
assert.equal(cc.features.automatic_sending,false);
assert.equal(cc.features.hidden_capture,false);
assert.equal(cc.features.stage_neutral_runtime_label,true);
assert.equal(cc.features.supporting_module_stability_claims,false);
assert.equal(cc.features.supporting_module_versions_hardcoded,false);

assert.deepEqual(raven.release_gate.stable_components,expected);
assert.equal(raven.privacy.raven_care_stable,true);
assert.equal(raven.privacy.command_center_version_synced,true);
assert.equal(raven.privacy.command_center_offline_first_one_click_launcher,true);
assert.equal(raven.privacy.command_center_launcher_network_requests,false);
assert.equal(raven.privacy.command_center_automatic_update_on_launch,false);
assert.equal(raven.privacy.command_center_manual_updater_requires_explicit_launch,true);
assert.equal(raven.privacy.command_center_bridge_health_explicit_only,true);
assert.equal(raven.privacy.command_center_automatic_agent_execution,false);
assert.equal(raven.privacy.command_center_automatic_mission_mutation,false);
assert.equal(raven.privacy.command_center_automatic_sending,false);
assert.equal(raven.privacy.command_center_runtime_frozen,true);
assert.equal(raven.privacy.command_center_stable,true);
for (const p of ['RAH-COMMAND-CENTER-V0.3.html','RAH-COMMAND-CENTER-VERSION.json','rah-command-center-core.js','DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','UPDATE-RAH-COMMAND-CENTER.ps1']) assert.ok(raven.files.includes(p));
assert.match(raven.summary,/Command Center v0\.3\.2 are stable/);
assert.match(raven.summary,/normal startup is offline-first/);

const snapshot=core.buildCoreSnapshot(raven,'manifest');
assert.equal(snapshot.stableCount,9);
assert.match(html,/PACKAGE MODULES/);
assert.match(html,/PACKAGED/);
assert.match(html,/Not checked\. CC v0\.3\.2 never probes the Bridge until you click the button\./);
assert.doesNotMatch(html,/v0\.3(?:\.2)? candidate/i);
assert.doesNotMatch(html,/Stable local supporting module/);
assert.doesNotMatch(html,/core\.EXTRA_COMPONENTS/);
assert.doesNotMatch(html,/\/agent\/run|setInterval\s*\(|navigator\.mediaDevices|getUserMedia|clipboard\.readText/i);
assert.match(launcher,/start "" "%CC_PAGE%"/);
assert.doesNotMatch(launcher,/Invoke-WebRequest|powershell|pwsh|raw\.githubusercontent\.com|https?:\/\//i);
console.log('RAH Command Center v0.3.3 updater-integrity candidate passed over frozen v0.3.2 runtime; exact nine Raven core components preserved.');
