import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const ps=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER-V2.ps1','utf8'),m=JSON.parse(fs.readFileSync('RAH-CC-UPDATER-V2-VERSION.json','utf8')),cc=JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8'));
test('Candidate inactive and authority neutral',()=>{assert.equal(m.stage,'feature-candidate');assert.equal(m.active_from_root_wrapper,false);assert.equal(m.authority_delta,'none');assert.equal(cc.version,'1.7.0');assert.deepEqual(m.command_center_authority.capabilities,['compute','storage','display','remote-desktop']);assert.deepEqual(m.command_center_authority.actions,['storage-summary.read','rustdesk.launch','rustdesk.connect']);assert.deepEqual(m.command_center_authority.business_routes,['/health','/actions','/storage','/launch/rustdesk','/handoff/rustdesk']);assert.equal(m.command_center_authority.new_authority,false)});
test('single verified immutable commit drives all network reads',()=>{assert.match(ps,/Resolve-VerifiedRepositoryCommit/);assert.match(ps,/commitInfo\.commit\.verification\.verified/);assert.match(ps,/\$RawBase="https:\/\/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$ResolvedCommit"/);assert.doesNotMatch(ps,/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$RepoBranch/);assert.equal(m.network_model.raw_mutable_main_downloads,false)});
test('full package is staged and hashed before install',()=>{assert.match(ps,/\$StageRoot=Join-Path/);assert.match(ps,/Assert-IntegrityManifest/);assert.match(ps,/Get-GitBlobSha1/);const stage=ps.indexOf('foreach($relative in $manifest.package_files)');const verified=ps.indexOf('packagefiler er staged');const install=ps.indexOf('New-Item -ItemType Directory -Path $BackupDir');assert.ok(stage>0&&verified>stage&&install>verified);assert.equal(m.package_integrity.package_file_count,26);assert.equal(m.package_integrity.hashed_file_count,25);assert.equal(m.package_integrity.verify_all_hashed_files_before_install,true)});
test('integrity self-contract is explicit',()=>{assert.equal(m.package_integrity.integrity_manifest_self_hashed,false);assert.equal(m.package_integrity.integrity_manifest_trusted_from_same_immutable_commit,true);assert.match(ps,/self_hashed-ne\$false/);assert.match(ps,/self_path-ne\$IntegrityManifestName/)});
test('fixed package allowlist and safe path boundary remain mandatory',()=>{assert.match(ps,/\$AllowedPackageFiles=@\(/);assert.match(ps,/Assert-FixedPackageContract/);assert.match(ps,/IsPathRooted/);assert.match(ps,/Contains\('\.\.'\)/);assert.match(ps,/StartsWith\(\$baseFull/);assert.match(ps,/duplikate filer/)});
test('rollback exists and manifest is installed after package files',()=>{assert.match(ps,/function Restore-OnFailure/);assert.match(ps,/Starter rollback av CC-filer/);const install=ps.lastIndexOf('foreach($relative in $manifest.package_files)');const manifestInstall=ps.indexOf('$manifestTarget=Get-SafeTargetPath',install);assert.ok(manifestInstall>install);assert.equal(m.installation_model.rollback_on_install_failure,true);assert.equal(m.installation_model.manifest_installed_last,true)});
test('Candidate does not claim root activation',()=>{assert.equal(m.known_transition_limit.root_updater_not_activated_in_candidate,true);assert.equal(m.known_transition_limit.stable_activation_requires_separate_promotion,true);assert.equal(m.known_transition_limit.existing_manual_cc_updater_remains_active_until_promotion,true)});
