import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
const m=JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8'));
const release=JSON.parse(fs.readFileSync('RAH-CC19-NODE13-STABLE-RELEASE.json','utf8'));
const up=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER.ps1','utf8');
const launcher=fs.readFileSync('DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','utf8');
const nodeBat=fs.readFileSync('START-RAH-NODE-AGENT.bat','utf8');
const nodeSh=fs.readFileSync('START-RAH-NODE-AGENT.sh','utf8');
const files=["RAH-COMMAND-CENTER-V1.9.html","RAH-COMMAND-CENTER-V1.9-CANDIDATE.html","rah-command-center-core-v1.9-candidate.js","rah-command-center-core-v1.9.js","RAH-CC19-IMMUTABLE-MUTATING-INTENT-CANDIDATE.json","RAH-CC19-NODE13-STABLE-RELEASE.json","RAH-COMMAND-CENTER-V1.8.html","RAH-COMMAND-CENTER-V1.8-CANDIDATE.html","RAH-COMMAND-CENTER-V1.7.html","RAH-COMMAND-CENTER-V1.7-CANDIDATE.html","RAH-COMMAND-CENTER-V1.2.html","rah-command-center-core.js","rah-command-center-core-v1.3.js","rah-command-center-core-v1.4.js","rah-command-center-core-v1.5-candidate.js","rah-command-center-core-v1.5.js","rah-command-center-core-v1.6-candidate.js","rah-command-center-core-v1.6.js","rah-command-center-core-v1.7-candidate.js","rah-command-center-core-v1.7.js","rah-command-center-core-v1.8-candidate.js","rah-command-center-core-v1.8.js","DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat","rah-node-agent.py","rah-node-agent-v0.9.py","rah-node-agent-v1.0-candidate.py","rah-node-agent-v1.0.py","rah-node-agent-v1.1-candidate.py","rah-node-agent-v1.1.py","rah-node-agent-v1.2-candidate.py","rah-node-agent-v1.3-candidate.py","rah-node-agent-v1.3.py","START-RAH-NODE-AGENT.bat","START-RAH-NODE-AGENT.sh","RAH-CC17-NODE13-STABLE-RELEASE.json","RAH-CC18-ONE-SHOT-MUTATING-APPROVAL-CANDIDATE.json","RAH-CC18-NODE13-STABLE-RELEASE.json"];

test('canonical v1.9 Stable package closure',()=>{assert.equal(m.version,'1.9.0');assert.equal(m.stage,'stable');assert.equal(m.entry,'RAH-COMMAND-CENTER-V1.9.html');assert.equal(m.runtime,'rah-command-center-core-v1.9.js');assert.equal(m.previous_stable_version,'1.8.0');assert.equal(m.stable_release_manifest,'RAH-CC19-NODE13-STABLE-RELEASE.json');assert.equal(m.canonical_package_generation,4);assert.equal(m.release_gate.status,'passed');assert.equal(m.release_gate.runtime_files_frozen,true);assert.equal(m.development_paused,true);assert.deepEqual(m.package_files,files);assert.equal(files.length,37);for(const f of files)assert.ok(fs.existsSync(f),f)});

test('canonical launcher is offline and opens v1.9 Stable',()=>{assert.match(launcher,/RAH-COMMAND-CENTER-V1\.9\.html/);assert.match(launcher,/v1\.9\.0 STABLE/);assert.doesNotMatch(launcher,/Invoke-WebRequest|curl\b|wget\b|https?:\/\//i)});

test('Node launchers retain exact Stable Node 1.3',()=>{assert.match(nodeBat,/rah-node-agent-v1\.3\.py/);assert.match(nodeSh,/rah-node-agent-v1\.3\.py/)});

test('manual updater pins exact immutable 37-file closure and v1.9 release',()=>{for(const f of files)assert.ok(up.includes('"'+f+'"'),f);assert.match(up,/Resolve-VerifiedRepositoryCommit/);assert.match(up,/commit\.verification\.verified/);assert.match(up,/Assert-FixedPackageContract/);assert.match(up,/Assert-StableReleaseContract/);assert.match(up,/manifest\.version-ne"1\.9\.0"/);assert.match(up,/RAH-CC19-NODE13-STABLE-RELEASE\.json/)});

test('canonical authority stays frozen and immutable intent policy is exact',()=>{assert.equal(release.commandCenterVersion,'1.9.0');assert.equal(release.nodeAgentVersion,'1.3.0');assert.equal(release.nodeRuntimeChange,false);assert.deepEqual(release.authoritySurface.capabilities,['compute','storage','display','remote-desktop']);assert.deepEqual(release.authoritySurface.actions,['storage-summary.read','rustdesk.launch','rustdesk.connect']);assert.deepEqual(release.authoritySurface.businessRoutes,['/health','/actions','/storage','/launch/rustdesk','/handoff/rustdesk']);const b=release.mutatingIntentBinding;assert.equal(b.bindsEndpointIpv4,true);assert.equal(b.bindsCapabilitySnapshot,true);assert.equal(b.bindsAdvertisedActionSnapshot,true);assert.equal(b.bindsApprovedActionSnapshot,true);assert.equal(b.memoryOnly,true);assert.equal(b.persistent,false);assert.equal(b.singleUse,true);assert.equal(b.storesRawTarget,false);assert.equal(m.features.immutable_mutating_intent_binding,true);assert.equal(m.features.mutating_intent_math_random_fallback,false)});
