import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const stable=require('../rah-command-center-core-v1.7.js');
const release=JSON.parse(fs.readFileSync('RAH-CC17-NODE13-STABLE-RELEASE.json','utf8'));
const gate=JSON.parse(fs.readFileSync('RAH-CC17-NODE13-STABLE-PROMOTION-GATE.json','utf8'));
const candidate=JSON.parse(fs.readFileSync('RAH-CC17-NODE13-TOKEN-PROOF-CANDIDATE.json','utf8'));
const html=fs.readFileSync('RAH-COMMAND-CENTER-V1.7.html','utf8');
function gitBlobSha(path){const body=fs.readFileSync(path);return crypto.createHash('sha1').update(Buffer.from(`blob ${body.length}\0`)).update(body).digest('hex')}
function verify(ref){assert.equal(gitBlobSha(ref.path),ref.gitBlobSha,`${ref.path} blob drifted`)}
const caps=['compute','storage','display','remote-desktop'],actions=['storage-summary.read','rustdesk.launch','rustdesk.connect'],routes=['/health','/actions','/storage','/launch/rustdesk','/handoff/rustdesk'];

test('Stable release identity and authority are exact',()=>{assert.equal(release.stage,'stable-release');assert.equal(release.authorityDelta,'none');assert.equal(release.commandCenterVersion,'1.7.0');assert.equal(release.nodeAgentVersion,'1.3.0');assert.equal(release.nodeActionsProtocol,'rah-node-actions-v7');assert.equal(release.authProtocol,'rah-node-auth-v2');assert.equal(release.policyId,'rah-capability-allowlist-v1');assert.deepEqual(release.authoritySurface,{capabilities:caps,actions,businessRoutes:routes,newBusinessRoutes:[]});assert.deepEqual(gate.authoritySurface,release.authoritySurface);assert.deepEqual(candidate.authoritySurface,release.authoritySurface);assert.equal(release.freezeAfterPromotion,true)});
test('Stable, Candidate and rollback blobs are pinned',()=>{for(const ref of Object.values(release.runtime))verify(ref);for(const ref of Object.values(release.pinnedCandidate))verify(ref);for(const ref of [release.directRollback.previousStableRelease,release.directRollback.commandCenterCore,release.directRollback.commandCenterHtml,release.directRollback.nodeAgent])verify(ref);for(const ref of Object.values(gate.candidate))verify(ref);for(const ref of Object.values(gate.targetStable).filter(v=>v&&typeof v==='object'&&v.path))verify(ref);for(const ref of [gate.directRollback.stableRelease,gate.directRollback.commandCenterCore,gate.directRollback.commandCenterHtml,gate.directRollback.nodeAgent])verify(ref)});
test('Stable core is strict wrapper over exact Candidate protocol',()=>{assert.equal(stable.CC_VERSION,'1.7.0');assert.equal(stable.NODE_ACTIONS_PROTOCOL,'rah-node-actions-v7');assert.equal(stable.NODE_AUTH_PROTOCOL,'rah-node-auth-v2');assert.equal(stable.ALLOWLIST_POLICY_ID,'rah-capability-allowlist-v1');assert.deepEqual([...stable.CAPABILITY_IDS],caps);assert.deepEqual([...stable.ACTION_IDS],actions);assert.deepEqual([...stable.AUTHENTICATED_PATHS],routes)});
test('Stable UI layers Stable core over pinned Candidate',()=>{assert.match(html,/RAH-COMMAND-CENTER-V1\.7-CANDIDATE\.html/);assert.match(html,/rah-command-center-core-v1\.7-candidate\.js/);assert.match(html,/rah-command-center-core-v1\.7\.js/);assert.match(html,/window\.RAHCommandCenterCoreV17/);assert.match(html,/CC 1\.7 STABLE/);assert.match(html,/Stable failed closed:/)});
test('release explicitly removes bearer LAN transport while retaining independent gates',()=>{assert.ok(release.securityDelta.some(x=>/bearer token is no longer transported/i.test(x)));for(const key of ['bearer-token-network-transport','bearer-fallback','new-capabilities','new-actions','new-routes','shell','generic-command-execution','generic-process-launch','generic-file-api','native-raven-remote-control-api'])assert.ok(release.forbiddenRuntimeExpansion.includes(key),key);for(const key of ['bearer-token','auth-nonce','auth-proof','action-challenge','node-local-approval-proof','raw-requester-context','password','rustdesk-peer-id'])assert.ok(release.forbiddenPersistence.includes(key),key)});
test('rollback is direct and migration-free',()=>{assert.equal(release.directRollback.commandCenterVersion,'1.6.0');assert.equal(release.directRollback.nodeAgentVersion,'1.2.0');assert.equal(release.directRollback.nodeActionsProtocol,'rah-node-actions-v6');assert.equal(release.directRollback.dataMigration,'none');assert.equal(release.directRollback.secretMigration,'none');assert.equal(release.directRollback.registryMigration,'none')});
