import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url),core=require('../rah-command-center-core-v1.8-candidate.js'),manifest=JSON.parse(fs.readFileSync('RAH-CC18-ONE-SHOT-MUTATING-APPROVAL-CANDIDATE.json','utf8')),html=fs.readFileSync('RAH-COMMAND-CENTER-V1.8-CANDIDATE.html','utf8');
const session='SessionId_abcdefghijklmnop',launchId='Approval_abcdefghijklmnopqrstuvwxyz1234567890',connectId='Approval_ZYXWVUTSRQPONMLKJIHGFEDCBA9876543210',peerDigest='0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
function nodeFor(action){let records=core.normalizeDeviceRegistry([{id:'node-one',label:'Node One',role:'Test',platform:'Linux',kind:'desktop',status:'unverified',source:'local',enrolled:true,endpointIp:'192.168.1.44',agentSessionId:session,capabilities:['remote-desktop'],advertisedActions:['rustdesk.launch','rustdesk.connect'],approvedActions:[]}]);records=core.approveDeviceAction(records,'node-one',action);return records[0]}

test('Candidate identity and authority are unchanged',()=>{assert.equal(core.CC_VERSION,'1.8.0-candidate');assert.equal(core.NODE_ACTIONS_PROTOCOL,'rah-node-actions-v7');assert.equal(core.NODE_AUTH_PROTOCOL,'rah-node-auth-v2');assert.deepEqual([...core.CAPABILITY_IDS],manifest.authoritySurface.capabilities);assert.deepEqual([...core.ACTION_IDS],manifest.authoritySurface.actions);assert.deepEqual([...core.AUTHENTICATED_PATHS],manifest.authoritySurface.businessRoutes);assert.deepEqual(manifest.authoritySurface.newCapabilities,[]);assert.deepEqual(manifest.authoritySurface.newActions,[]);assert.deepEqual(manifest.authoritySurface.newBusinessRoutes,[])});
test('only mutating actions require one-shot approval',()=>{assert.equal(core.isOneShotApprovalRequired('storage-summary.read'),false);assert.equal(core.isOneShotApprovalRequired('rustdesk.launch'),true);assert.equal(core.isOneShotApprovalRequired('rustdesk.connect'),true);assert.deepEqual([...core.MUTATING_ACTION_IDS],['rustdesk.launch','rustdesk.connect'])});
test('ticket binds current device session action and target digest',()=>{let now=1000;const ledger=new core.OneShotMutatingApprovalLedger({now:()=>now,idFactory:()=>launchId}),node=nodeFor('rustdesk.launch'),ticket=ledger.approve(node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST);assert.ok(ticket);assert.equal(ticket.deviceId,'node-one');assert.equal(ticket.agentSessionId,session);assert.equal(ticket.actionId,'rustdesk.launch');assert.equal(ticket.targetDigest,core.EMPTY_TARGET_DIGEST);assert.equal(ticket.expiresAt,91000);assert.equal(ledger.snapshot().rawTargetsStored,false);assert.equal(ledger.snapshot().persistent,false)});
test('ticket is consumed exactly once before reuse',()=>{const ledger=new core.OneShotMutatingApprovalLedger({idFactory:()=>launchId}),node=nodeFor('rustdesk.launch'),ticket=ledger.approve(node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST);assert.equal(ledger.consume(ticket.approvalId,node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST),true);assert.equal(ledger.consume(ticket.approvalId,node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST),false);assert.equal(ledger.snapshot().outstandingCount,0)});
test('binding mismatch consumes ticket and cannot be corrected later',()=>{const ledger=new core.OneShotMutatingApprovalLedger({idFactory:()=>connectId}),node=nodeFor('rustdesk.connect'),ticket=ledger.approve(node,'rustdesk.connect',peerDigest);assert.ok(ticket);assert.equal(ledger.consume(ticket.approvalId,node,'rustdesk.connect','ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'),false);assert.equal(ledger.consume(ticket.approvalId,node,'rustdesk.connect',peerDigest),false)});
test('session change and revoked session approval fail closed',()=>{const ledger=new core.OneShotMutatingApprovalLedger({idFactory:()=>launchId}),node=nodeFor('rustdesk.launch'),ticket=ledger.approve(node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST);const changed={...node,agentSessionId:'SessionId_qrstuvwxyz123456'};assert.equal(ledger.consume(ticket.approvalId,changed,'rustdesk.launch',core.EMPTY_TARGET_DIGEST),false);const ledger2=new core.OneShotMutatingApprovalLedger({idFactory:()=>connectId}),node2=nodeFor('rustdesk.connect'),ticket2=ledger2.approve(node2,'rustdesk.connect',peerDigest),revoked=core.revokeDeviceAction([node2],'node-one','rustdesk.connect')[0];assert.equal(ledger2.consume(ticket2.approvalId,revoked,'rustdesk.connect',peerDigest),false)});
test('expired tickets are removed and max outstanding is bounded',()=>{let now=0,n=0;const ledger=new core.OneShotMutatingApprovalLedger({now:()=>now,ttlMs:100,maxOutstanding:2,idFactory:()=>`Approval_${String(++n).padStart(32,'A')}`}),node=nodeFor('rustdesk.launch');assert.ok(ledger.approve(node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST));assert.ok(ledger.approve(node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST));assert.equal(ledger.approve(node,'rustdesk.launch',core.EMPTY_TARGET_DIGEST),null);now=101;assert.equal(ledger.snapshot().outstandingCount,0)});
test('secure ID validation has no Math.random fallback',()=>{const source=fs.readFileSync('rah-command-center-core-v1.8-candidate.js','utf8');assert.doesNotMatch(source,/Math\.random/);assert.match(source,/cryptoObj\.getRandomValues/);assert.equal(core.sanitizeApprovalId('short'),'');assert.equal(core.sanitizeTargetDigest(peerDigest),peerDigest)});
test('raw RustDesk target never enters one-shot ledger or browser storage',()=>{assert.match(html,/const digest=await targetDigest\(action,peer\),ticket=ledger\.approve\(d,action,digest\)/);assert.match(html,/return sha\(clean\)/);assert.doesNotMatch(html,/ledger\.approve\([^\n]*peer/);assert.doesNotMatch(html,/localStorage\.setItem\([^\n]*(?:peerId|approvalId|armed|requesterContext|nodeToken|mutToken)/i);assert.match(html,/persistableDeviceRegistry\(devices\)/)});
test('UI consumes one-shot before Node-local confirmation intent',()=>{const consume=html.indexOf('ledger.consume(approvalId,d,action,digest)'),intent=html.indexOf('core.localApprovalIntentRequest(d,action');assert.ok(consume>0&&intent>consume,`consume=${consume} intent=${intent}`);assert.match(html,/One-shot consumed\. Waiting for independent Node-local confirmation/)});
test('storage remains read-only and does not use one-shot ledger',()=>{const start=html.indexOf('async function storage()'),end=html.indexOf('async function targetDigest',start),section=html.slice(start,end);assert.ok(start>0&&end>start);assert.doesNotMatch(section,/ledger\.(?:approve|consume)/);assert.match(section,/storage-summary\.read/)});
test('browser retains token-proof no-bearer boundary and existing routes only',()=>{assert.match(html,/nodeAuthInitRequest/);assert.match(html,/buildAuthCanonicalFromRequest/);assert.match(html,/attachAuthProof/);assert.doesNotMatch(html,/Authorization\s*:\s*['"]Bearer/i);for(const forbidden of ['/shell','/command','/files','/action/run','/remote-control'])assert.equal(html.includes(forbidden),false,forbidden)});
test('Candidate contract explicitly forbids persistence and authority expansion',()=>{assert.equal(manifest.oneShotApproval.memoryOnly,true);assert.equal(manifest.oneShotApproval.persistent,false);assert.equal(manifest.oneShotApproval.singleUse,true);assert.equal(manifest.oneShotApproval.consumeBeforeNodeLocalConfirmation,true);assert.equal(manifest.oneShotApproval.storesRawTarget,false);assert.equal(manifest.oneShotApproval.mathRandomFallback,false);for(const item of ['new-capability','new-action','new-business-route','persistent-mutating-approval','ticket-reuse','ticket-target-raw-storage','bearer-token-network-transport','shell','generic-command-execution','generic-process-launch','generic-file-api','native-raven-remote-control-api'])assert.ok(manifest.forbidden.includes(item),item)});
