import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('RAH-RAVEN-MISSION-CONTROL.html','utf8');
const policy=fs.readFileSync('raven-checkpoint-policy.js','utf8');
const studio=fs.readFileSync('RAH-RAVEN-START.html','utf8');
const core=fs.readFileSync('RAH-RAVEN-CORE-DEMO.html','utf8');
const agent=fs.readFileSync('RAH-RAVEN-AGENT-RUNNER.html','utf8');
const missionManifest=JSON.parse(fs.readFileSync('RAH-RAVEN-MISSION-CONTROL-VERSION.json','utf8'));
assert.equal(missionManifest.version,'2.9.0');
assert.equal(missionManifest.stage,'stable');
assert.equal(missionManifest.development_paused,true);
assert.equal(missionManifest.change_policy,'bugfix-only-until-explicit-reopen');
assert.equal(missionManifest.stable_release_gate?.status,'passed');
assert.equal(missionManifest.stable_release_gate?.runtime_files_frozen,true);
assert.equal(missionManifest.next_milestone,null);


function between(text,startMarker,endMarker,label){const start=text.indexOf(startMarker);assert.notEqual(start,-1,`${label}: start marker missing`);const bodyStart=start+startMarker.length;const end=text.indexOf(endMarker,bodyStart);assert.notEqual(end,-1,`${label}: end marker missing`);return text.slice(bodyStart,end)}

assert.match(html,/RAH Raven Mission Control v2\.9/);
assert.match(html,/v2\.9 · LOCAL FIRST/);
assert.match(html,/Ett prosjekt\. Ett neste steg\./);
assert.match(html,/<script src="raven-checkpoint-policy\.js"><\/script>/);
assert.match(html,/const Checkpoint=window\.RAHCheckpointPolicy/);
assert.match(html,/Checkpoint\.contextSnapshot\(state,m,blocker\)/);
assert.match(html,/Checkpoint\.recommendSnapshot\(snapshot,"mission-control"\)/);
assert.match(html,/snapshot\.nextStep/);
assert.match(html,/snapshot\.relation/);
assert.match(html,/function activeProjectIndex\(\)\{return Checkpoint\.activeProjectIndex\(state\)\}/);
assert.doesNotMatch(html,/function missionMatchesProject\(/);
assert.doesNotMatch(html,/function missionProjectIndex\(/);
assert.doesNotMatch(html,/function recommendedCheckpoint\(/);
assert.doesNotMatch(html,/function missionOpen\(m\)/);
assert.match(html,/function updateRecommendedCheckpoint\(checkpoint\)/);
assert.match(html,/id="recommendedCheckpoint"/);
assert.match(html,/id="nextAction"/);
assert.match(html,/id="missionStart"/);
assert.match(html,/id="projectMissionState"/);
assert.match(html,/id="missionProjectLink"/);
assert.match(html,/relation\.status/);
assert.match(html,/relation\.detail/);
assert.match(html,/relation\.missionProjectHref/);
assert.match(policy,/function contextSnapshot\(/);
assert.match(policy,/function recommendSnapshot\(/);
assert.match(policy,/function projectMissionRelation\(/);
assert.match(policy,/✓ SAMME PROSJEKT/);
assert.match(policy,/⚠ ULIKT PROSJEKT/);
assert.match(policy,/MISSIONSPROSJEKT IKKE FUNNET/);
assert.match(policy,/BLOCKER/);
assert.match(policy,/MISSION MISMATCH/);
assert.match(policy,/MISSION PROJECT UNKNOWN/);
assert.match(policy,/FORTSETT MISSION/);
assert.match(policy,/VELG MISSION/);
assert.match(html,/function openStep\(index\)/);
assert.match(html,/function completeStep\(index\)/);
assert.match(html,/function recordResult\(\)/);
assert.match(html,/function setBlocker\(\)/);
assert.match(html,/step\.lastOpenedAt=now\(\)/);
assert.match(html,/step\.done=true/);
assert.match(html,/confirm\(`Markere/);
assert.match(html,/mission-control-v2\.9/);
assert.match(html,/function createCouncilMission\(record\)/);
assert.match(html,/function createChronicleMission\(loop\)/);
assert.match(html,/presetId:"chronicle-resume"/);
assert.match(html,/\/chronicle\/brief\?hours=24/);
assert.match(html,/function normalizeBridgeBase\(raw\)/);
assert.match(html,/function bridgeBase\(\)\{return normalizeBridgeBase\(/);
const normalizeBody=between(html,'function normalizeBridgeBase(raw){','function bridgeBase()','bridge boundary');
const normalizeBridgeBase=new Function('raw',normalizeBody.replace(/\n\s*}\s*$/,'') );
assert.equal(normalizeBridgeBase('http://127.0.0.1:18765'),'http://127.0.0.1:18765');
assert.equal(normalizeBridgeBase('http://localhost:18765/'),'http://localhost:18765');
assert.equal(normalizeBridgeBase('https://localhost:18765'),'https://localhost:18765');
assert.equal(normalizeBridgeBase('http://[::1]:18765'),'http://[::1]:18765');
for(const bad of ['https://example.com','http://192.168.1.10:18765','file:///tmp/bridge','http://user:pass@127.0.0.1:18765','http://127.0.0.1:18765/private','http://127.0.0.1:18765?x=1','http://127.0.0.1:18765#x']) assert.throws(()=>normalizeBridgeBase(bad));
const chronicleBody=between(html,'async function loadChronicleContext(){','function latestChronicleLoop()','chronicle context');
assert.match(chronicleBody,/fetch\(`\$\{bridgeBase\(\)\}\/chronicle\/brief\?hours=24`/);
const updateBody=between(html,'function updateRecommendedCheckpoint(checkpoint){','function renderProjectMissionRelation(relation)','update checkpoint');
assert.match(updateBody,/button\.href=checkpoint\.href/);
assert.doesNotMatch(updateBody,/localStorage\.setItem/);
assert.doesNotMatch(updateBody,/activeProject\s*=/);
assert.doesNotMatch(updateBody,/activeMission\s*=/);
assert.doesNotMatch(updateBody,/\.done\s*=\s*true/);
const relationBody=between(html,'function renderProjectMissionRelation(relation){','async function loadChronicleContext()','relation');
assert.doesNotMatch(relationBody,/Checkpoint\.projectMissionRelation/);
assert.match(relationBody,/relation\.status/);
assert.match(relationBody,/relation\.detail/);
assert.doesNotMatch(relationBody,/SAMME PROSJEKT/);
assert.doesNotMatch(relationBody,/ULIKT PROSJEKT/);
assert.doesNotMatch(relationBody,/localStorage\.setItem/);
assert.doesNotMatch(relationBody,/activeProject\s*=/);
assert.doesNotMatch(relationBody,/activeMission\s*=/);
assert.doesNotMatch(relationBody,/\.done\s*=\s*true/);
assert.match(studio,/mission:\{name:'Mission Control',url:'RAH-RAVEN-MISSION-CONTROL\.html'\}/);
assert.match(core,/href="RAH-RAVEN-MISSION-CONTROL\.html">Åpne Mission/);
assert.match(agent,/read-only-allowlist/);
assert.match(agent,/confirm:true/);
assert.match(agent,/Ingen vilkårlig kommando/);
console.log('Raven Mission Control v2.9 stable local Bridge boundary, shared Context Snapshot and safe mission controls passed.');
