import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('RAH-RAVEN-MISSION-CONTROL.html','utf8');
const policy=fs.readFileSync('raven-checkpoint-policy.js','utf8');
const studio=fs.readFileSync('RAH-RAVEN-START.html','utf8');
const core=fs.readFileSync('RAH-RAVEN-CORE-DEMO.html','utf8');
const agent=fs.readFileSync('RAH-RAVEN-AGENT-RUNNER.html','utf8');

function between(text,startMarker,endMarker,label){const start=text.indexOf(startMarker);assert.notEqual(start,-1,`${label}: start marker missing`);const bodyStart=start+startMarker.length;const end=text.indexOf(endMarker,bodyStart);assert.notEqual(end,-1,`${label}: end marker missing`);return text.slice(bodyStart,end)}

assert.match(html,/RAH Raven Mission Control v2\.6/);
assert.match(html,/v2\.6 · LOCAL FIRST/);
assert.match(html,/Ett prosjekt\. Ett neste steg\./);
assert.match(html,/<script src="raven-checkpoint-policy\.js"><\/script>/);
assert.match(html,/const Checkpoint=window\.RAHCheckpointPolicy/);
assert.match(html,/Checkpoint\.recommend\(state,m,blocker,"mission-control"\)/);
assert.match(html,/function activeProjectIndex\(\)\{return Checkpoint\.activeProjectIndex\(state\)\}/);
assert.match(html,/function missionMatchesProject\(project,m\)\{return Checkpoint\.missionMatchesProject\(state,m,activeProjectIndex\(\),project\)\}/);
assert.match(html,/function missionProjectIndex\(m\)\{return Checkpoint\.resolveMissionProjectIndex\(state,m\)\}/);
assert.doesNotMatch(html,/function recommendedCheckpoint\(/);
assert.doesNotMatch(html,/function missionOpen\(m\)/);
assert.match(html,/function updateRecommendedCheckpoint\(checkpoint\)/);
assert.match(html,/id="recommendedCheckpoint"/);
assert.match(html,/id="nextAction"/);
assert.match(html,/id="missionStart"/);
assert.match(html,/id="projectMissionState"/);
assert.match(html,/id="missionProjectLink"/);
assert.match(html,/SAMME PROSJEKT/);
assert.match(html,/ULIKT PROSJEKT/);
assert.match(html,/Ingen automatisk bytting/);
assert.match(policy,/BLOCKER/);
assert.match(policy,/MISSION MISMATCH/);
assert.match(policy,/MISSION PROJECT UNKNOWN/);
assert.match(policy,/FORTSETT MISSION/);
assert.match(policy,/VELG MISSION/);
assert.match(html,/function openStep\(index\)/);
assert.match(html,/function completeStep\(index\)/);
assert.match(html,/function recordResult\(\)/);
assert.match(html,/function setBlocker\(\)/);
assert.match(html,/step\.lastOpenedAt=now\(\)/);
assert.match(html,/step\.done=true/);
assert.match(html,/confirm\(`Markere/);
assert.match(html,/mission-control-v2\.6/);
assert.match(html,/function createCouncilMission\(record\)/);
assert.match(html,/function createChronicleMission\(loop\)/);
assert.match(html,/presetId:"chronicle-resume"/);
assert.match(html,/\/chronicle\/brief\?hours=24/);
const updateBody=between(html,'function updateRecommendedCheckpoint(checkpoint){','function renderProjectMissionRelation(project,m)','update checkpoint');
assert.match(updateBody,/button\.href=checkpoint\.href/);
assert.doesNotMatch(updateBody,/localStorage\.setItem/);
assert.doesNotMatch(updateBody,/activeProject\s*=/);
assert.doesNotMatch(updateBody,/activeMission\s*=/);
assert.doesNotMatch(updateBody,/\.done\s*=\s*true/);
const relationBody=between(html,'function renderProjectMissionRelation(project,m){','async function loadChronicleContext()','relation');
assert.match(relationBody,/missionProjectIndex\(m\)/);
assert.doesNotMatch(relationBody,/activeProject\s*=/);
assert.doesNotMatch(relationBody,/activeMission\s*=/);
assert.doesNotMatch(relationBody,/\.done\s*=\s*true/);
assert.match(studio,/mission:\{name:'Mission Control',url:'RAH-RAVEN-MISSION-CONTROL\.html'\}/);
assert.match(core,/href="RAH-RAVEN-MISSION-CONTROL\.html">Åpne Mission/);
assert.match(agent,/read-only-allowlist/);
assert.match(agent,/confirm:true/);
assert.match(agent,/Ingen vilkårlig kommando/);
console.log('Raven Mission Control v2.6 shared checkpoint module and safe mission controls passed.');
