import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync('RAH-RAVEN-CORE-DEMO.html', 'utf8');
const vision = fs.readFileSync('raven-vision-core.js', 'utf8');
const council = fs.readFileSync('raven-council.js', 'utf8');
const sync = fs.readFileSync('raven-chronicle-sync.js', 'utf8');
const agentPage = fs.readFileSync('RAH-RAVEN-AGENT-RUNNER.html', 'utf8');
const memoryPage = fs.readFileSync('RAH-RAVEN-MEMORY-SYNC.html', 'utf8');
const agentRunner = fs.readFileSync('desktop-bridge/agent_runner.py', 'utf8');
const bridge = fs.readFileSync('desktop-bridge/raven_bridge.py', 'utf8');

assert.match(html, /Raven Core Workflow v1\.12/);
assert.match(html, /Vision → Project Brain → Council → Mission Control → Agent Runner → Memory Sync/);
assert.match(html, /Én kontrollert arbeidsflyt i syv steg/);
assert.match(html, /Raven Context Snapshot/);
assert.match(html, /raven-checkpoint-policy\.js/);
assert.match(html, /raven-vision-core\.js\?v=0\.1/);
assert.match(html, /raven-council\.js\?v=0\.1/);
assert.match(html, /raven-chronicle-sync\.js\?v=0\.1/);
assert.match(html, /rah\.raven\.vision\.core\.history\.v1/);
assert.match(html, /rah\.raven\.council\.history\.v1/);
assert.match(html, /rah\.raven\.agent\.runner\.history\.v1/);
assert.match(html, /rah\.command\.center/);
assert.match(html, /http:\/\/127\.0\.0\.1:18765/);
assert.match(html, /Analyser et bilde du velger selv/);
assert.match(html, /Ingen skjult skjermfangst/);
assert.doesNotMatch(html, /Analyser ett valgt vindu/);
assert.doesNotMatch(html, /Vision fanger bare/);
assert.match(html, /applyVisionToRahState/);
assert.match(html, /applyRecordToRahState/);
assert.match(html, /attachMission:true/);
assert.match(html, /En aktiv mission finnes/);
assert.match(html, /agentRunId===agent\.id/);
assert.match(html, /SYNC\.buildEvents/);
assert.match(html, /SYNC\.SYNC_KEY/);
assert.match(html, /Automatisk Memory Sync: NEI/);
assert.match(html, /Vilkårlige kommandoer: NEI/);
assert.match(html, /Automatiske risikohandlinger: NEI/);
assert.match(html, /Bilder lagret i Brain: NEI/);
assert.match(html, /RAH-RAVEN-AGENT-RUNNER\.html/);
assert.match(html, /RAH-RAVEN-MEMORY-SYNC\.html/);
assert.match(html, /id="visionChatGPTHandoff"/);
assert.match(html, /RAH-RAVEN-VISION-CORE\.html\?mode=chatgpt/);
assert.match(html, /DEL BILDE MED CHATGPT/);
assert.match(html, /id="copyCoreStatus"/);
assert.match(html, /id="downloadCoreStatus"/);
assert.match(html, /KOPIER STATUS/);
assert.match(html, /STATUS TXT/);
assert.match(html, /id="chatgptHandoffCenter"/);
assert.match(html, /id="chatgptHandoffVision"/);
assert.match(html, /ChatGPT Handoff/);
assert.match(html, /ÅPNE VISION FOR BILDE/);

assert.match(vision, /imageStored: false/);
assert.match(council, /buildPlanningMission/);
assert.match(sync, /rah\.raven\.chronicle\.sync\.v1/);
assert.match(sync, /Prompt og analysesvar lagret i Chronicle: nei/);
assert.match(memoryPage, /Eksplisitt synkronisering/);
assert.match(memoryPage, /confirmSync/);
assert.match(agentPage, /payload\.read_only\s*!==\s*true/);
assert.match(agentPage, /payload\.files_modified\s*!==\s*false/);
assert.match(agentPage, /payload\.automatic_actions\s*!==\s*false/);
assert.match(agentPage, /confirm:true/);
assert.match(agentRunner, /shell=False/);
assert.match(agentRunner, /"files_modified": False/);
assert.match(bridge, /@app\.post\("\/lm\/chat"\)/);
assert.match(bridge, /import agent_runner/);

console.log('Raven Core workflow v1.12 source-aware ChatGPT handoff validation passed.');
