import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
const policy=fs.readFileSync("raven-checkpoint-policy.js","utf8");
function between(text,start,end){const a=text.indexOf(start);assert.notEqual(a,-1);const b=text.indexOf(end,a+start.length);assert.notEqual(b,-1);return text.slice(a+start.length,b)}
assert.match(html,/RAH Raven Core Workflow v1\.10/);
assert.match(html,/Core v1\.10 · HANDOFF RESUME/);
assert.match(html,/Raven Context Snapshot/);
assert.match(html,/id="contextSnapshotPanel"/);
assert.match(html,/id="coreDirectionStatus"/);
for(const id of ["pipelineDirection","pipelineDirectionMeta","operationalDirection","operationalDirectionMeta","contextNextActionCard","contextNextAction","contextNextActionDetail","coreContinue"]) assert.match(html,new RegExp(`id="${id}"`));
assert.match(html,/PIPELINE-STATUS/);
assert.match(html,/OPERATIV RETNING · STYRER FORTSETT/);
assert.match(html,/NESTE HANDLING · INGEN AUTOMATIKK/);
assert.match(html,/«Neste handling» forklarer hva du kan gjøre der/);
assert.match(html,/<script src="raven-checkpoint-policy\.js"><\/script>/);
assert.match(html,/CHECKPOINT\.contextSnapshot\(state,mission,missionBlocker\(mission\)\)/);
assert.match(html,/CHECKPOINT\.recommendSnapshot\(snapshot,"core"\)/);
assert.match(html,/function corePipelineState\(/);
assert.match(html,/function renderCoreDirection\(/);
assert.match(html,/function nextActionHint\(/);
const pipeline=between(html,"function corePipelineState(","function renderCoreDirection(");
assert.doesNotMatch(pipeline,/localStorage/);
assert.doesNotMatch(pipeline,/activeProject\s*=/);
assert.doesNotMatch(pipeline,/activeMission\s*=/);
assert.doesNotMatch(pipeline,/\.done\s*=\s*true/);
assert.doesNotMatch(pipeline,/\/agent\/run/);
const direction=between(html,"function renderCoreDirection(pipeline,checkpoint){","function nextActionHint(snapshot,checkpoint){");
assert.match(direction,/pipelineDirection/);
assert.match(direction,/operationalDirection/);
assert.doesNotMatch(direction,/coreContinue/);
assert.doesNotMatch(direction,/localStorage/);
const nextAction=between(html,"function nextActionHint(snapshot,checkpoint){","function renderContextSnapshot(snapshot,checkpoint){");
for(const kind of ["BLOCKER","MISSION MISMATCH","MISSION PROJECT UNKNOWN","MISSION","PROJECT"]) assert.match(nextAction,new RegExp(`checkpoint\.kind===\"${kind}\"`));
assert.match(nextAction,/snapshot\.nextStep/);
assert.match(nextAction,/snapshot\.blocker/);
assert.doesNotMatch(nextAction,/localStorage/);
assert.doesNotMatch(nextAction,/writeState\(/);
assert.doesNotMatch(nextAction,/activeProject\s*=/);
assert.doesNotMatch(nextAction,/activeMission\s*=/);
assert.doesNotMatch(nextAction,/\.done\s*=\s*true/);
assert.doesNotMatch(nextAction,/\/agent\/run/);
assert.doesNotMatch(nextAction,/coreContinue/);
assert.doesNotMatch(nextAction,/\.href\s*=/);
const context=between(html,"function renderContextSnapshot(snapshot,checkpoint){","function buildReport(){");
assert.match(context,/const nextAction=nextActionHint\(snapshot,checkpoint\)/);
assert.match(context,/contextNextAction/);
assert.match(context,/contextNextActionDetail/);
assert.match(context,/\$\("coreContinue"\)\.href=checkpoint\.href/);
assert.doesNotMatch(context,/nextAction\.href/);
assert.doesNotMatch(context,/pipeline\.href/);
assert.doesNotMatch(context,/localStorage\.setItem/);
assert.doesNotMatch(context,/writeState\(/);
assert.doesNotMatch(context,/activeProject\s*=/);
assert.doesNotMatch(context,/activeMission\s*=/);
assert.doesNotMatch(context,/\.done\s*=\s*true/);
assert.doesNotMatch(context,/\/agent\/run/);
assert.equal((html.match(/id="coreContinue"/g)||[]).length,1);
assert.doesNotMatch(html,/coreContinue[^\n]*onclick=/);
assert.match(policy,/function contextSnapshot\(/);
assert.match(policy,/function recommendSnapshot\(/);
console.log("Raven Core v1.10 keeps Context Snapshot FORTSETT authority with source-aware handoff return.");
