import assert from "node:assert/strict";
import fs from "node:fs";
const core=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
const now=fs.readFileSync("RAH-RAVEN-NOW-V2.html","utf8");
const studio=fs.readFileSync("RAH-RAVEN-START.html","utf8");
const receiptPolicy=fs.readFileSync("raven-handoff-receipt.js","utf8");
assert.match(core,/RAH Raven Core Workflow v1\.12/);
assert.match(now,/RAH Raven Now v2\.17/);
assert.match(studio,/RAH Raven Studio v2\.8/);
assert.match(core,/id="handoffResumePanel"/);
assert.match(core,/id="handoffResume"/);
assert.match(core,/function handoffResumeHref\(session\)/);
assert.match(core,/if\(!session\?\.source\|\|!session\.status\)return ""/);
assert.match(core,/params\.set\("handoffReturn","ready"\)/);
assert.match(core,/params\.set\("handoffStatus","ready"\)/);
assert.match(core,/if\(session\.image\)params\.set\("handoffImage","ready"\)/);
assert.match(core,/resumePanel\.hidden=!resumeHref/);
assert.match(core,/FORTSETT TIL \$\{session\.source\.key==="now"\?"RAVEN NOW":"RAVEN STUDIO"\}/);
assert.match(now,/id="handoffReturnNotice"/);
assert.match(studio,/id="handoffReturnNotice"/);
assert.match(now,/function renderHandoffReceipt\(params\)/);
assert.match(studio,/function renderHandoffReceipt\(params\)/);
const resumeFn=core.split("function handoffResumeHref(session){",2)[1].split("function renderHandoffSession(){",1)[0];
assert.doesNotMatch(resumeFn,/localStorage|sessionStorage|fetch\(|writeState\(|activeMission\s*=|activeProject\s*=|\.done\s*=/);
for(const text of [now,studio]){
  assert.doesNotMatch(text,/api\.openai\.com|chatgpt\.com\/backend|openai\.com\/v1/i);
}
assert.match(receiptPolicy,/Dette bekrefter ikke mottak i ChatGPT/);
assert.doesNotMatch(receiptPolicy,/api\.openai\.com|chatgpt\.com\/backend|openai\.com\/v1/i);
assert.match(now,/id="continueButton" href="RAH-RAVEN-MISSION-CONTROL\.html"/);
console.log("Raven Handoff Resume stays status-gated and URL-only while the shared receipt policy describes local return state.");
