import assert from "node:assert/strict";
import fs from "node:fs";
const now=fs.readFileSync("RAH-RAVEN-NOW-V2.html","utf8");
const studio=fs.readFileSync("RAH-RAVEN-START.html","utf8");
const core=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
const vision=fs.readFileSync("RAH-RAVEN-VISION-CORE.html","utf8");
assert.match(now,/id="nowChatgptHandoff" href="RAH-RAVEN-CORE-DEMO\.html\?handoffFrom=now#chatgptHandoffCenter"/);
assert.match(studio,/id="studioChatgptHandoff" href="RAH-RAVEN-CORE-DEMO\.html\?handoffFrom=studio#chatgptHandoffCenter"/);
assert.match(core,/RAH Raven Core Workflow v1\.9/);
assert.match(vision,/RAH Raven Vision Core v0\.5/);
assert.match(core,/id="handoffSourceReturn"/);
assert.match(core,/function handoffSource\(value\)/);
assert.match(core,/value==="now"/);
assert.match(core,/value==="studio"/);
assert.match(core,/session\.source\.href/);
assert.match(core,/session\.source\.label/);
assert.match(core,/handoffFrom=\$\{session\.source\.key\}/);
assert.match(vision,/const handoffFrom = \["now","studio"\]\.includes\(query\.get\("handoffFrom"\)\)/);
assert.match(vision,/if\(handoffFrom\)params\.push\(`handoffFrom=\$\{handoffFrom\}`\)/);
const sourceFn=core.split("function handoffSource(value){",2)[1].split("function handoffSession(){",1)[0];
assert.doesNotMatch(sourceFn,/localStorage|sessionStorage|fetch\(|writeState\(|history\.replaceState|activeMission\s*=|activeProject\s*=/);
const sessionFn=core.split("function handoffSession(){",2)[1].split("function renderHandoffSession(){",1)[0];
assert.doesNotMatch(sessionFn,/localStorage|sessionStorage|fetch\(|writeState\(/);
const nowTag=(now.match(/<a class="btn" id="nowChatgptHandoff"[^>]*>/)||[])[0]||"";
const studioTag=(studio.match(/<a class="btn" id="studioChatgptHandoff"[^>]*>/)||[])[0]||"";
for(const tag of [nowTag,studioTag])assert.doesNotMatch(tag,/onclick=|data-launch=|handoffStatus=|handoffImage=/);
assert.doesNotMatch(core+vision,/api\.openai\.com|chatgpt\.com\/backend|openai\.com\/v1/i);
console.log("Raven 2.0.24 source-aware handoff return is allowlisted, URL-only and navigation-only.");
