import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
const policy=fs.readFileSync("raven-checkpoint-policy.js","utf8");
function between(text,start,end){const a=text.indexOf(start);assert.notEqual(a,-1);const b=text.indexOf(end,a+start.length);assert.notEqual(b,-1);return text.slice(a+start.length,b)}
assert.match(html,/RAH Raven Core Workflow v1\.1/);
assert.match(html,/Raven Context Snapshot/);
assert.match(html,/id="contextSnapshotPanel"/);
assert.match(html,/<script src="raven-checkpoint-policy\.js"><\/script>/);
assert.match(html,/const CHECKPOINT = window\.RAHCheckpointPolicy/);
assert.match(html,/CHECKPOINT\.contextSnapshot\(state,mission,missionBlocker\(mission\)\)/);
assert.match(html,/CHECKPOINT\.recommendSnapshot\(snapshot,"core"\)/);
assert.match(html,/id="contextProject"/);
assert.match(html,/id="contextMission"/);
assert.match(html,/id="contextBlocker"/);
assert.match(html,/id="contextNext"/);
assert.match(html,/id="contextRelation"/);
assert.match(html,/id="contextCheckpointButton"/);
const body=between(html,"function renderContextSnapshot(snapshot,checkpoint){","function buildReport(){");
for(const marker of ["snapshot.activeProject","snapshot.mission","snapshot.blocker","snapshot.nextStep","snapshot.relation","checkpoint.href"]) assert.match(body,new RegExp(marker.replace(".","\\.")));
assert.doesNotMatch(body,/localStorage\.setItem/);
assert.doesNotMatch(body,/writeState\(/);
assert.doesNotMatch(body,/activeProject\s*=/);
assert.doesNotMatch(body,/activeMission\s*=/);
assert.doesNotMatch(body,/\.done\s*=\s*true/);
assert.doesNotMatch(body,/\/agent\/run/);
assert.match(html,/saveLatestVision/);
assert.match(html,/sendLatestMission/);
assert.match(html,/confirm\("En aktiv mission finnes/);
assert.match(policy,/function contextSnapshot\(/);
assert.match(policy,/function recommendSnapshot\(/);
console.log("Raven Core v1.1 shared Context Snapshot read-only panel passed.");
