import assert from "node:assert/strict";
import fs from "node:fs";
const core=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
const now=fs.readFileSync("RAH-RAVEN-NOW-V2.html","utf8");
const studio=fs.readFileSync("RAH-RAVEN-START.html","utf8");
assert.match(core,/RAH Raven Core Workflow v1\.10/);
assert.match(now,/RAH Raven Now v2\.13/);
assert.match(studio,/RAH Raven Studio v2\.4/);
assert.match(core,/id="handoffResumePanel"/);
assert.match(core,/id="handoffResume"/);
assert.match(core,/function handoffResumeHref\(session\)/);
assert.match(core,/if\(!session\?\.source\|\|!session\.status\)return ""/);
assert.match(core,/params\.set\("handoffReturn","ready"\)/);
assert.match(core,/params\.set\("handoffStatus","ready"\)/);
assert.match(core,/if\(session\.image\)params\.set\("handoffImage","ready"\)/);
assert.match(core,/resumePanel\.hidden=!resumeHref/);
assert.match(core,/FORTSETT TIL \$\{session\.source\.key==="now"\?"RAVEN NOW":"RAVEN STUDIO"\}/);
assert.match(now,/id="handoffReturnNotice"/);
assert.match(studio,/id="handoffReturnNotice"/);
assert.match(now,/params\.get\('handoffReturn'\)==='ready'/);
assert.match(studio,/handoffParams\.get\('handoffReturn'\)==='ready'/);
assert.match(now,/Raven-data er ikke endret/);
assert.match(studio,/Ingen Studio-state er endret/);
const resumeFn=core.split("function handoffResumeHref(session){",2)[1].split("function renderHandoffSession(){",1)[0];
assert.doesNotMatch(resumeFn,/localStorage|sessionStorage|fetch\(|writeState\(|activeMission\s*=|activeProject\s*=|\.done\s*=/);
const nowReturn=now.split("if(params.get('handoffReturn')==='ready')",2)[1].split("$('refresh').onclick",1)[0];
assert.doesNotMatch(nowReturn,/localStorage|sessionStorage|writeState\(|continueButton.*href|activeMission\s*=|activeProject\s*=|\.done\s*=/);
const studioReturn=studio.split("if(handoffParams.get('handoffReturn')==='ready')",2)[1].split("const FAVORITES_KEY",1)[0];
assert.doesNotMatch(studioReturn,/localStorage|sessionStorage|setItem\(|removeItem\(|fetch\(|data-launch/);
assert.match(now,/id="continueButton" href="RAH-RAVEN-MISSION-CONTROL\.html"/);
assert.doesNotMatch(core+now+studio,/api\.openai\.com|chatgpt\.com\/backend|openai\.com\/v1/i);
console.log("Raven 2.0.25 Handoff Resume is status-gated, allowlisted, URL-only and navigation-only.");
