import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync("RAH-RAVEN-CHRONICLE-LIVE.html","utf8");
const server=fs.readFileSync("desktop-bridge/server_v17.py","utf8");
const component=JSON.parse(fs.readFileSync("RAH-RAVEN-CHRONICLE-VERSION.json","utf8"));
const master=JSON.parse(fs.readFileSync("RAH-RAVEN-VERSION.json","utf8"));
assert.match(html,/CHRONICLE LIVE · DESKTOP BRIDGE v1\.7/);
assert.match(html,/RAH Raven Chronicle v1\.7 · lokal-first · menneskestyrt samtykke/);
assert.match(html,/const BASE='http:\/\/127\.0\.0\.1:18765'/);
assert.match(html,/post\('\/chronicle\/session\/start'/);
assert.doesNotMatch(html,/setInterval\([^\n]*session\/start|refresh\([^)]*session\/start/);
assert.equal(component.product,"RAH Raven Chronicle");
assert.equal(component.version,"1.7.1");
assert.equal(component.previous_stable_version,"1.7.0");
assert.equal(component.stage,"stable");
assert.equal(component.runtime_feature_change,false);
assert.equal(component.features.foreign_browser_origin_guard,true);
assert.equal(component.features.chronicle_routes_local_browser_origin_only,true);
assert.equal(component.features.cross_origin_mutation_blocked,true);
assert.equal(component.features.cors_wildcard,false);
assert.equal(component.features.visible_session_required_for_foreground_read,true);
assert.equal(component.features.paused_blocks_foreground_read,true);
assert.equal(component.features.keylogging,false);
assert.equal(component.features.clipboard_capture,false);
assert.equal(component.features.audio_capture,false);
assert.equal(component.features.camera_capture,false);
assert.equal(component.features.automatic_sending,false);
assert.equal(component.next_milestone,null);
assert.equal(component.development_paused,true);
assert.equal(component.change_policy,"bugfix-only-until-explicit-reopen");
assert.equal(component.stable_release_gate.status,"passed");
assert.equal(component.stable_release_gate.gate_version,"1.1.0");
assert.equal(component.stable_release_gate.runtime_files_frozen,true);
assert.match(server,/from server_v16 import HOST, LOCAL_BROWSER_ORIGINS, PORT, app/);
assert.match(server,/CHRONICLE_PROTECTED_PREFIX = "\/chronicle"/);
assert.match(server,/protect_chronicle_local_apis/);
assert.match(server,/origin and origin not in LOCAL_BROWSER_ORIGINS/);
const stable={raven_vision:"0.6",raven_council:"0.3",agent_runner:"0.3",memory_sync:"0.2",mission_control:"2.9",project_focus:"2.4",raven_core:"1.12",raven_now:"2.17",raven_studio:"2.8"};
assert.deepEqual(master.release_gate.stable_components,stable);
assert.equal(master.privacy.raven_chronicle_foreign_browser_origin_guard,true);
assert.equal(master.privacy.raven_chronicle_routes_local_browser_origin_only,true);
assert.equal(master.privacy.raven_chronicle_cross_origin_mutation_blocked,true);
assert.equal(master.privacy.raven_chronicle_cors_wildcard,false);
assert.equal(master.privacy.raven_chronicle_bugfix_candidate,false);
assert.equal(master.privacy.raven_chronicle_candidate_over_previous_stable,false);
assert.equal(master.privacy.raven_chronicle_stable,true);
assert.equal(master.privacy.raven_fristvakt_stable,true);
assert.equal(master.privacy.case_center_stable,true);
assert.equal(master.privacy.command_center_stable,true);
console.log("Raven Chronicle v1.7.1 Stable local-origin boundary passed with runtime frozen.");
