import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
assert.match(html,/RAH Raven Core Workflow v1\.11/);
assert.match(html,/Core v1\.11 · HANDOFF RECALL/);
for(const id of ["chatgptHandoffCenter","handoffSessionState","handoffStatusState","handoffImageState","handoffSessionSummary","resetHandoffSession","copyCoreStatus","downloadCoreStatus","chatgptHandoffVision","supportShareStatus"])assert.match(html,new RegExp(`id="${id}"`));
assert.match(html,/MANUELL · URL ONLY · INGEN AUTO-SENDING/);
assert.match(html,/KOPIER STATUS/);
assert.match(html,/STATUS TXT/);
assert.match(html,/RAH-RAVEN-VISION-CORE\.html\?mode=chatgpt/);
assert.match(html,/ÅPNE VISION FOR BILDE/);
assert.match(html,/Ingen bilder, prompts eller analysesvar inkluderes/);
assert.match(html,/Start med status/);
assert.match(html,/Ingenting sendes automatisk/);
assert.match(html,/RAH Raven 2\.0\.25 · Core v1\.11 support snapshot/);
assert.match(html,/\$\("copyCoreStatus"\)\.onclick=copySupportSnapshot/);
assert.match(html,/\$\("downloadCoreStatus"\)\.onclick=downloadSupportSnapshot/);
assert.doesNotMatch(html,/chatgptHandoffVision[^>]*onclick=/);
assert.equal((html.match(/id="copyCoreStatus"/g)||[]).length,1);
assert.equal((html.match(/id="downloadCoreStatus"/g)||[]).length,1);
assert.equal((html.match(/id="chatgptHandoffVision"/g)||[]).length,1);
assert.doesNotMatch(html,/api\.openai\.com/i);
assert.doesNotMatch(html,/chatgpt\.com\/backend/i);
console.log("Raven Core v1.11 adds source-aware URL-only handoff return without automatic sending.");
