import assert from 'node:assert/strict';
import fs from 'node:fs';

const html=fs.readFileSync('RAH-RAVEN-NOW-V2.html','utf8');
const policy=fs.readFileSync('raven-checkpoint-policy.js','utf8');
function between(text,startMarker,endMarker,label){const start=text.indexOf(startMarker);assert.notEqual(start,-1,`${label}: start marker missing`);const bodyStart=start+startMarker.length;const end=text.indexOf(endMarker,bodyStart);assert.notEqual(end,-1,`${label}: end marker missing`);return text.slice(bodyStart,end)}

assert.match(html,/RAH Raven Now v2\.10/);
assert.match(html,/v2\.10 · READ ONLY/);
assert.match(html,/Dagens viktigste mission/);
assert.match(html,/Project Switcher/);
assert.match(html,/Systemstatus/);
assert.match(html,/<script src="raven-checkpoint-policy\.js"><\/script>/);
assert.match(html,/const Checkpoint=window\.RAHCheckpointPolicy/);
assert.match(html,/Checkpoint\.contextSnapshot\(s,m,block\)/);
assert.match(html,/Checkpoint\.recommendSnapshot\(snapshot,'now'\)/);
assert.match(html,/snapshot\.nextStep/);
assert.match(html,/snapshot\.relation/);
assert.match(html,/snapshot\.missionProjectIndex/);
assert.match(html,/snapshot\.missionOpen/);
assert.doesNotMatch(html,/Checkpoint\.recommend\(s,m,block,'now'\)/);
assert.doesNotMatch(html,/Checkpoint\.projectMissionRelation\(s,m,activeIndex\)/);
assert.doesNotMatch(html,/function recommendedCheckpoint\(/);
assert.doesNotMatch(html,/function activeProjectIndex\(s\)/);
assert.doesNotMatch(html,/function missionOpen\(m\)/);
assert.doesNotMatch(html,/function missionMatchesProject\(/);
assert.doesNotMatch(html,/function nextStep\(m\)/);
assert.match(html,/function updateRecommendedCheckpoint\(checkpoint\)/);
assert.match(html,/function updateProjectMissionRelation\(relation\)/);
assert.match(html,/function updateContinue\(m,active,snapshot\)/);
assert.match(html,/id="recommendedCheckpoint"/);
assert.match(html,/id="recommendedCheckpointButton"/);
assert.match(html,/id="continueButton"/);
assert.match(html,/id="missionProjectButton"/);
assert.match(html,/id="projectMissionRelation"/);
assert.match(html,/relation\.status/);
assert.match(html,/relation\.detail/);
assert.match(html,/relation\.missionProjectHref/);
assert.match(html,/project-badges/);
assert.match(html,/mission-tag/);
assert.match(html,/isMissionProject=snapshot\.missionOpen&&projectIndex===missionIndex/);
assert.match(html,/recentProjects\(s,context\).*context\.missionProjectIndex/s);
assert.match(html,/id="todayMission"/);
assert.match(html,/id="activeProjectBadge"/);
assert.match(html,/id="bridgeState"/);
assert.match(html,/\/chronicle\/brief\?hours=24/);
assert.match(html,/Raven Now v2 er fortsatt skrivebeskyttet/);
assert.match(policy,/function contextSnapshot\(/);
assert.match(policy,/function recommendSnapshot\(/);
assert.match(policy,/function projectMissionRelation\(/);
assert.match(policy,/✓ SAMME PROSJEKT/);
assert.match(policy,/⚠ ULIKT PROSJEKT/);
assert.match(policy,/MISSIONSPROSJEKT IKKE FUNNET/);
assert.match(policy,/Ingen prosjektbytte skjer automatisk/);

const relationBody=between(html,'function updateProjectMissionRelation(relation){','function updateRecommendedCheckpoint(checkpoint)','relation presentation');
assert.match(relationBody,/relation\.status/);
assert.match(relationBody,/relation\.detail/);
assert.doesNotMatch(relationBody,/localStorage\.setItem/);
assert.doesNotMatch(relationBody,/activeProject\s*=/);
assert.doesNotMatch(relationBody,/activeMission\s*=/);
assert.doesNotMatch(relationBody,/\.done\s*=\s*true/);

assert.doesNotMatch(html,/localStorage\.setItem\(STATE_KEY/);
assert.doesNotMatch(html,/\bs\.activeProject\s*=(?!=)/);
assert.doesNotMatch(html,/\bstate\.activeProject\s*=(?!=)/);
assert.doesNotMatch(html,/\bactiveMission\s*=(?!=)/);
assert.doesNotMatch(html,/function completeStep\s*\(/);
assert.doesNotMatch(html,/step\.done\s*=\s*true/);
assert.doesNotMatch(html,/\/agent\/run/);
assert.doesNotMatch(html,/createChronicleMission/);
console.log('Raven Now v2.10 shared Context Snapshot and read-only navigation passed.');
