import assert from 'node:assert/strict';
import fs from 'node:fs';

const html=fs.readFileSync('RAH-RAVEN-NOW-V2.html','utf8');
const policy=fs.readFileSync('raven-checkpoint-policy.js','utf8');
assert.match(html,/RAH Raven Now v2\.8/);
assert.match(html,/v2\.8 · READ ONLY/);
assert.match(html,/Dagens viktigste mission/);
assert.match(html,/Project Switcher/);
assert.match(html,/Systemstatus/);
assert.match(html,/<script src="raven-checkpoint-policy\.js"><\/script>/);
assert.match(html,/const Checkpoint=window\.RAHCheckpointPolicy/);
assert.match(html,/Checkpoint\.recommend\(s,m,block,'now'\)/);
assert.match(html,/Checkpoint\.activeProjectIndex\(s\)/);
assert.match(html,/Checkpoint\.resolveMissionProjectIndex\(s,m\)/);
assert.match(html,/Checkpoint\.missionOpen\(m\)/);
assert.match(html,/Checkpoint\.missionMatchesProject\(s,m,activeIndex,active\)/);
assert.doesNotMatch(html,/function recommendedCheckpoint\(/);
assert.doesNotMatch(html,/function activeProjectIndex\(s\)/);
assert.doesNotMatch(html,/function missionOpen\(m\)/);
assert.match(html,/function updateRecommendedCheckpoint\(checkpoint\)/);
assert.match(html,/function updateContinue\(s,m,block,activeIndex,active,missionIndex\)/);
assert.match(html,/id="recommendedCheckpoint"/);
assert.match(html,/id="recommendedCheckpointButton"/);
assert.match(html,/id="continueButton"/);
assert.match(html,/id="missionProjectButton"/);
assert.match(html,/id="projectMissionRelation"/);
assert.match(html,/SAMME PROSJEKT/);
assert.match(html,/MISSION ≠ AKTIVT PROSJEKT/);
assert.match(html,/MISSIONSPROSJEKT IKKE FUNNET/);
assert.match(html,/project-badges/);
assert.match(html,/mission-tag/);
assert.match(html,/isMissionProject=Checkpoint\.missionOpen\(m\)&&projectIndex===missionIndex/);
assert.match(html,/recentProjects\(s,m\).*Checkpoint\.resolveMissionProjectIndex\(s,m\)/s);
assert.match(html,/id="todayMission"/);
assert.match(html,/id="activeProjectBadge"/);
assert.match(html,/id="bridgeState"/);
assert.match(html,/\/chronicle\/brief\?hours=24/);
assert.match(html,/Raven Now v2 er fortsatt skrivebeskyttet/);
assert.match(policy,/MISSION MISMATCH/);
assert.match(policy,/FORTSETT AKTIVT PROSJEKT/);
assert.match(policy,/Ingen prosjektbytte skjer automatisk/);
assert.doesNotMatch(html,/localStorage\.setItem\(STATE_KEY/);
assert.doesNotMatch(html,/\bs\.activeProject\s*=(?!=)/);
assert.doesNotMatch(html,/\bstate\.activeProject\s*=(?!=)/);
assert.doesNotMatch(html,/\bactiveMission\s*=(?!=)/);
assert.doesNotMatch(html,/function completeStep\s*\(/);
assert.doesNotMatch(html,/step\.done\s*=\s*true/);
assert.doesNotMatch(html,/\/agent\/run/);
assert.doesNotMatch(html,/createChronicleMission/);
console.log('Raven Now v2.8 shared checkpoint module and read-only navigation passed.');
