import assert from "node:assert/strict";
import fs from "node:fs";
const core=fs.readFileSync("RAH-RAVEN-CORE-DEMO.html","utf8");
const vision=fs.readFileSync("RAH-RAVEN-VISION-CORE.html","utf8");
assert.match(core,/RAH Raven Core Workflow v1\.11/);
assert.match(vision,/RAH Raven Vision Core v0\.5/);
for(const id of ["handoffSessionState","handoffStatusState","handoffImageState","handoffSessionSummary","resetHandoffSession"])assert.match(core,new RegExp(`id="${id}"`));
assert.match(core,/function handoffSession\(\)/);
assert.match(core,/function renderHandoffSession\(\)/);
assert.match(core,/function setHandoffMarker\(/);
assert.match(core,/function resetHandoffSession\(\)/);
assert.match(core,/handoffStatus/);
assert.match(core,/handoffImage/);
assert.match(core,/history\.replaceState/);
const coreHandoff=core.split("function handoffSession(){",2)[1].split("async function copySupportSnapshot(){",1)[0];
assert.doesNotMatch(coreHandoff,/localStorage|sessionStorage|fetch\(|writeState\(|activeMission\s*=|activeProject\s*=/);
assert.match(core,/setHandoffMarker\("handoffStatus"\)/);
assert.match(core,/RAH-RAVEN-VISION-CORE\.html\?mode=chatgpt&return=core/);
assert.match(vision,/const returnToCore = query\.get\("return"\) === "core"/);
assert.match(vision,/const statusReadyFromCore = query\.get\("status"\) === "ready"/);
assert.match(vision,/function updateReturnHandoff\(imageReady=false\)/);
assert.match(vision,/id="returnHandoffCore"/);
assert.match(vision,/handoffStatus=ready/);
assert.match(vision,/handoffImage=ready/);
const returnFn=vision.split("function updateReturnHandoff(imageReady=false){",2)[1].split("async function copyImageToClipboard()",1)[0];
assert.doesNotMatch(returnFn,/localStorage|sessionStorage|fetch\(|navigator\.clipboard|capture|imageData/);
const setImage=vision.split("function setImage(",2)[1].split("function readFile(",1)[0];
assert.doesNotMatch(setImage,/updateReturnHandoff\(true\)/);
assert.equal((vision.match(/updateReturnHandoff\(true\)/g)||[]).length,2);
assert.doesNotMatch(core+vision,/api\.openai\.com|chatgpt\.com\/backend|openai\.com\/v1/i);
console.log("Raven 2.0.25 handoff session uses URL markers only and marks image progress only after explicit share actions.");
