import assert from "node:assert/strict";
import fs from "node:fs";

const moduleText = fs.readFileSync("system-health-v1.7.js", "utf8");
const indexText = fs.readFileSync("index.html", "utf8");
const component = JSON.parse(fs.readFileSync("RAH-RAVEN-SYSTEM-HEALTH-VERSION.json", "utf8"));
const master = JSON.parse(fs.readFileSync("RAH-RAVEN-VERSION.json", "utf8"));

const hookMatches = indexText.match(/system-health-v1\.7\.js\?v=1\.7/g) || [];
assert.equal(hookMatches.length, 1);
assert.match(moduleText, /const VERSION = "1\.7\.0"/);
assert.match(moduleText, /const BRIDGE = "http:\/\/127\.0\.0\.1:18765"/);
assert.doesNotMatch(moduleText, /127\.0\.0\.1:8765|port 8765/);
assert.match(moduleText, /const LM_STUDIO = "http:\/\/127\.0\.0\.1:1234"/);
assert.match(moduleText, /rahRunHealthCheck/);
assert.match(moduleText, /window\.runRavenSystemHealth = runFullCheck/);
assert.doesNotMatch(moduleText, /setTimeout\(runFullCheck|setInterval\(runFullCheck/);
assert.match(moduleText, /saveHistory\(\{ time: summary\.time, ready: summary\.ready, failed: summary\.failed, total: summary\.total \}\)/);
assert.doesNotMatch(moduleText, /\n\s*saveHistory\(summary\);/);
assert.doesNotMatch(moduleText, /service_role/i);

assert.equal(component.product, "RAH Raven System Health");
assert.equal(component.version, "1.7.0");
assert.equal(component.stage, "candidate");
assert.equal(component.runtime_feature_change, false);
assert.equal(component.features.command_center_panel_loaded, true);
assert.equal(component.features.explicit_check_only, true);
assert.equal(component.features.automatic_check, false);
assert.equal(component.features.browser_bridge_loopback_only, true);
assert.equal(component.features.bridge_base, "http://127.0.0.1:18765");
assert.equal(component.features.external_bridge_addresses_allowed, false);
assert.equal(component.features.lm_studio_loopback_only, true);
assert.equal(component.features.history_summary_only, true);
assert.equal(component.features.history_service_details_stored, false);
assert.equal(component.features.screenshot_capture, false);
assert.equal(component.features.password_storage, false);
assert.equal(component.features.secret_key_storage, false);
assert.equal(component.features.automatic_sending, false);
assert.equal(component.features.capability_set_changed, false);
assert.equal(component.next_milestone, "stable-gate");

const stable = {raven_vision:"0.6",raven_council:"0.3",agent_runner:"0.3",memory_sync:"0.2",mission_control:"2.9",project_focus:"2.4",raven_core:"1.12",raven_now:"2.17",raven_studio:"2.8"};
assert.deepEqual(master.release_gate.stable_components, stable);
assert.equal(master.privacy.raven_chronicle_stable, true);
assert.equal(master.privacy.system_health_explicit_check_only, true);
assert.equal(master.privacy.system_health_automatic_check, false);
assert.equal(master.privacy.system_health_local_bridge_only, true);
assert.equal(master.privacy.system_health_external_bridge_addresses_allowed, false);
assert.equal(master.privacy.system_health_canonical_bridge_port_synced, true);
assert.equal(master.privacy.system_health_history_summary_only, true);
assert.equal(master.privacy.system_health_history_service_details_stored, false);
assert.equal(master.privacy.system_health_stable, false);
console.log("Raven System Health v1.7 explicit-check candidate contract passed.");
