import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const m=JSON.parse(fs.readFileSync('RAH-COMMAND-CENTER-VERSION.json','utf8')),release=JSON.parse(fs.readFileSync('RAH-CC17-NODE13-STABLE-RELEASE.json','utf8')),integrity=JSON.parse(fs.readFileSync('RAH-CC17-PACKAGE-INTEGRITY.json','utf8')),updaterRelease=JSON.parse(fs.readFileSync('RAH-CC-UPDATER-V2-STABLE-RELEASE.json','utf8')),rootUpdater=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER.ps1','utf8'),v2=fs.readFileSync('UPDATE-RAH-COMMAND-CENTER-V2.ps1','utf8'),launcher=fs.readFileSync('DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','utf8'),nodeBat=fs.readFileSync('START-RAH-NODE-AGENT.bat','utf8'),nodeSh=fs.readFileSync('START-RAH-NODE-AGENT.sh','utf8');
const files=['RAH-COMMAND-CENTER-V1.7.html','RAH-COMMAND-CENTER-V1.7-CANDIDATE.html','RAH-COMMAND-CENTER-V1.2.html','rah-command-center-core.js','rah-command-center-core-v1.3.js','rah-command-center-core-v1.4.js','rah-command-center-core-v1.5-candidate.js','rah-command-center-core-v1.5.js','rah-command-center-core-v1.6-candidate.js','rah-command-center-core-v1.6.js','rah-command-center-core-v1.7-candidate.js','rah-command-center-core-v1.7.js','DOBBELTKLIKK-HER-START-RAH-COMMAND-CENTER.bat','rah-node-agent.py','rah-node-agent-v0.9.py','rah-node-agent-v1.0-candidate.py','rah-node-agent-v1.0.py','rah-node-agent-v1.1-candidate.py','rah-node-agent-v1.1.py','rah-node-agent-v1.2-candidate.py','rah-node-agent-v1.3-candidate.py','rah-node-agent-v1.3.py','START-RAH-NODE-AGENT.bat','START-RAH-NODE-AGENT.sh','RAH-CC17-NODE13-STABLE-RELEASE.json','RAH-CC17-PACKAGE-INTEGRITY.json'];
test('canonical v1.7 package closure now has integrity generation 3',()=>{assert.equal(m.version,'1.7.0');assert.equal(m.stage,'stable');assert.equal(m.entry,'RAH-COMMAND-CENTER-V1.7.html');assert.equal(m.runtime,'rah-command-center-core-v1.7.js');assert.equal(m.package_integrity_manifest,'RAH-CC17-PACKAGE-INTEGRITY.json');assert.equal(m.canonical_package_generation,3);assert.equal(m.release_gate.status,'passed');assert.equal(m.release_gate.gate_version,'2.1.0');assert.equal(m.release_gate.runtime_files_frozen,true);assert.deepEqual(m.package_files,files);for(const f of files)assert.ok(fs.existsSync(f),f)});
test('offline launcher still opens v1.7 Stable and Node launcher still opens Node 1.3',()=>{assert.match(launcher,/RAH-COMMAND-CENTER-V1\.7\.html/);assert.doesNotMatch(launcher,/Invoke-WebRequest|curl\b|wget\b|https?:\/\//i);assert.match(nodeBat,/rah-node-agent-v1\.3\.py/);assert.match(nodeSh,/rah-node-agent-v1\.3\.py/)});
test('root CC updater is offline hash-verifying V2 wrapper with no auto legacy fallback',()=>{assert.match(rootUpdater,/UPDATE-RAH-COMMAND-CENTER-V2\.ps1/);assert.match(rootUpdater,/RAH-CC-UPDATER-V2-STABLE-RELEASE\.json/);assert.match(rootUpdater,/Get-GitBlobSha1/);assert.match(rootUpdater,/startes aldri automatisk/);assert.doesNotMatch(rootUpdater,/Invoke-WebRequest|Invoke-RestMethod|raw\.githubusercontent\.com|api\.github\.com|https?:\/\//i);assert.doesNotMatch(rootUpdater,/&\s*\$LegacyPath/)});
test('CC Updater V2 uses immutable SHA, full stage, integrity and rollback',()=>{assert.match(v2,/Resolve-VerifiedRepositoryCommit/);assert.match(v2,/commitInfo\.commit\.verification\.verified/);assert.match(v2,/\$RawBase="https:\/\/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$ResolvedCommit"/);assert.match(v2,/Assert-IntegrityManifest/);assert.match(v2,/Get-GitBlobSha1/);assert.match(v2,/packagefiler er staged/);assert.match(v2,/Restore-OnFailure/);assert.doesNotMatch(v2,/raw\.githubusercontent\.com\/\$RepoOwner\/\$RepoName\/\$RepoBranch/)});
test('package integrity manifest has exact 25 non-self Git blob pins',()=>{assert.equal(integrity.product,'RAH Raven Command Center Package Integrity');assert.equal(integrity.schemaVersion,1);assert.equal(integrity.canonical_version,'1.7.0');assert.equal(integrity.algorithm,'git-blob-sha1');assert.equal(integrity.self_path,'RAH-CC17-PACKAGE-INTEGRITY.json');assert.equal(integrity.self_hashed,false);assert.equal(integrity.hashed_files.length,25);const paths=integrity.hashed_files.map(x=>x.path);assert.deepEqual(paths,files.filter(x=>x!==integrity.self_path));for(const row of integrity.hashed_files)assert.match(row.gitBlobSha,/^[0-9a-f]{40}$/)});
test('Updater V2 Stable release and CC authority remain exact',()=>{assert.equal(updaterRelease.stage,'stable-release');assert.equal(updaterRelease.active_from_root_wrapper,true);assert.equal(updaterRelease.integrityManifest.path,'RAH-CC17-PACKAGE-INTEGRITY.json');assert.deepEqual(release.authoritySurface.capabilities,['compute','storage','display','remote-desktop']);assert.deepEqual(release.authoritySurface.actions,['storage-summary.read','rustdesk.launch','rustdesk.connect']);assert.deepEqual(release.authoritySurface.businessRoutes,['/health','/actions','/storage','/launch/rustdesk','/handoff/rustdesk']);assert.equal(release.authoritySurface.newBusinessRoutes.length,0)});
